### ISSUE TITLE
normalize url paths before making a request

### ISSUE THREAD

**Issue by jaybuff** [Netflix-Skunkworks/go-jira#1]
https://issues.apache.org/jira//rest/api/2/issue/MESOS-1123 returns a 404, but https://issues.apache.org/jira/rest/api/2/issue/MESOS-1123 works :(

I had this problem with this config:

    $ cat ~/.jira.d/config.yml
    endpoint: https://issues.apache.org/jira/

Perhaps you can simply strip any trailing slashes from endpoint if they exists.

**Comment by jaybuff** [comment]
I looked, net/url doesn't have a normalize function (bummer).  I found https://github.com/PuerkitoBio/purell but it's just a bunch of regexes and it's complete overkill.

**Comment by coryb** [comment]
It might be easier to just trim off any trailing / when I read the endpoint property from the config files, I try to find something.
Thanks,
-Cory

**Comment by coryb** [comment]
I just went with a simple TrimRight, seems to work.
-Cory
