### ISSUE TITLE
Edit command fails because of `reporter` field

### ISSUE THREAD

**Issue by elsassph** [Netflix-Skunkworks/go-jira#105]
Default edit template gives the reporter but it has to be removed to be able to push the edit.

     2017-08-24T09:07:06.872+01:00 ERROR [cli.go:421] Field reporter is not editable

**Comment by coryb** [comment]
I will have to do some research to find out if it is possible to determine that a field is editable or not so that we can dynamically enable/disable these fields.  For now you might want to just export the `edit` template and customize it for your own requirements:
https://github.com/Netflix-Skunkworks/go-jira#templates

**Comment by elsassph** [comment]
Yes I edited the template, though I find odd to have `reporter` as an editable field by default - also why updating fields that didn't change?

**Comment by coryb** [comment]
I could be wrong, but I thought reporter was editable by default on standard (non customized) Jira installs.

As for why the field is submitted when not edited .. `go-jira` is dumb.  It does no analysis on the documents returned from the editors, it just passes it through to the Jira APIs.   I have been rewriting `go-jira` over the last few months, perhaps we can make the new version smarter in time.

**Comment by elsassph** [comment]
I don't see a use case for editing the reporter so it could be commented out by default, like the comments.

**Comment by coryb** [comment]
I will edit reporter sometimes when I open an issue on a users behalf and forget to add reporter when I create the issue.  Curious what you see for the `reporter` edit metadata. Could you run something like:
```
$ jira editmeta <ISSUE> | jq .fields.reporter
```

For me this shows:
```
{
  "autoCompleteUrl": "$jiraEndpoint/rest/api/latest/user/search?username=",
  "key": "reporter",
  "name": "Reporter",
  "operations": [
    "set"
  ],
  "required": true,
  "schema": {
    "system": "reporter",
    "type": "user"
  }
}
```
Which implies that I can set the value.

**Comment by coryb** [comment]
Btw, I think the template is just dumb. This is the current default template:
https://github.com/Netflix-Skunkworks/go-jira/blob/master/templates.go#L84

I have been working on a rewrite and as part of that I fixed the template:
https://github.com/Netflix-Skunkworks/go-jira/blob/v1/jiracli/templates.go#L262

So specifically we only show the reporter field when that field shows up in the edit metadata:
```
{{- if .meta.fields.reporter}}
  reporter:
    name: {{ if .overrides.reporter }}{{ .overrides.reporter }}{{else if .fields.reporter}}{{ .fields.reporter.name }}{{end}}{{end}}
```
Which I think would fix your issue.  I will look into get that update backported to the master branch.

**Comment by coryb** [comment]
Updated the default template for edit, released here:
https://github.com/Netflix-Skunkworks/go-jira/releases/latest

**Comment by elsassph** [comment]
Edit meta gives me nothing :/
```
{
    "fields": {}
}
```

**Comment by elsassph** [comment]
Edit now gives me only `summary` and `description` as editable fields by default - maybe our JIRA is a bit locked down bit certainly can't edit even online the reporter.
