### ISSUE TITLE
.fields.labels is empty in list mode, but shows in view

### ISSUE THREAD

**Issue by rbuckland** [Netflix-Skunkworks/go-jira#106]
When I view an issue 

`jira ls -q 'issue = PROJ-123' -t debug`

I do not see any `.fields.labels`

but I do see them under 

`jira view PROJ-123 -t debug`

How do I do about adding these fields to the list view ? (I wish to modify the template of a table, to include labels)

**Comment by rbuckland** [comment]
Found it ..

In config.yml .. `queryfields: summary,created,updated,priority,status,reporter,assignee,labels` 

(in my executable config.yml) 

```
 echo "queryfields: summary,created,updated,priority,status,reporter,assignee,labels"
```

**Comment by ryran** [comment]
I'm trying to do the exact same thing -- add the labels field to a copy of the table template -- and I understand that I can see labels with `jira view -t debug` (and not `jira ls -t debug`), but I don't understand your solution @rbuckland ...

Something about the ls command doesn't get details about labels, I guess? To my modified table template, I've added:
```
  {{- if .fields.labels -}}
    {{- cell .fields.labels -}}
  {{- else -}}
    {{- cell "<none>" -}}
  {{- end -}}
```

..but of course that unsurprisingly doesn't work. I mean, why would it ... when `-t debug` also doesn't show labels. Anyone have any hints?
