### ISSUE TITLE
Keyring integration not working if default keyring is not named "Default"

### ISSUE THREAD

**Issue by bartlibert** [Netflix-Skunkworks/go-jira#108]
Apparently, this application started using its own version of the tmc/keyring library, so with the new version I'm hit with a bug that was fixed in the upstream tmc/keyring but apparently is not yet in this version.
The bug is this one: https://github.com/tmc/keyring/issues/11
It was fixed here: https://github.com/tmc/keyring/commit/06e6283d50adc5f8fcdb3cdf33ee1244d4400ae1

It would be nice if this was also incorporated in go-jira (or if the upstream version was used again, if possible of course, you probably have a good reason to "fork" it)

**Comment by coryb** [comment]
Hey, thanks for the heads-up.  I am not really using a personal fork, it is just vendored library for dependency management using the `glide` tool.  That said, glide seems to have an issue understanding that the upstream repo has changed and refuses to updating my vendored dependencies.  I will try to get this resolved today.

**Comment by coryb** [comment]
Hey, I have updated dependencies and released a new version:
https://github.com/Netflix-Skunkworks/go-jira/releases/latest
Hopefully it works for you.

**Comment by bartlibert** [comment]
It works perfectly now, thanks for the quick fix!
(And I learned something new about go !)
