### ISSUE TITLE
Fixing client certificate auth in v1

### ISSUE THREAD

**Issue by jshirley-stripe** [Netflix-Skunkworks/go-jira#109]
Hiya!

I just upgraded to v1, and it breaks our existing `unixproxy` login option. The way we connect and authenticate to JIRA is via a client certificate and an authenticating proxy and plugin (it works surprisingly well!).

Basically with this setup we want to bypass and assume we will be authenticated, but I can't seem to figure out the right options. Is this not supported now?

If it's a regression I'm happy to throw together a fix, but wanted to ask first -- I can gate this behind an option easily I think.

Thanks!

```
~/$GOPATH/s/g/N/go-jira.v0: ./jira view TEST-1234
# Works as expected
~/$GOPATH/s/g/N/go-jira.v1: ./jira view TEST-1234
? Jira Password [admin]:  ********
ERROR Login failed
```

**Comment by jshirley-stripe** [comment]
Actually, this is now working… I'm not sure why that is, but it's probably something that I messed up on my end!

**Comment by coryb** [comment]
Okay, there might be something I missed in the refactor, so not impossible.  I have no way to test this currently, I did the best I could to ensure that I did not break this use case.  So keep an eye out for issues and hopefully we can get them sorted.
