### ISSUE TITLE
Custom commands don't work under windows

### ISSUE THREAD

**Issue by rattboi** [Netflix-Skunkworks/go-jira#110]
Hi there,

It looks like custom commands don't work under windows because Go doesn't implement syscall.exec under windows. This library that you use uses that as the default and only script executor, and so it fails.

See issue coryb/kingpeon#1

**Comment by coryb** [comment]
Interesting, do you get an error message or does it just silently exit?

Surprised windows does not implement syscall.exec. The implementation in the library is adjustable I can can swap out the default exec handler, maybe it could/should just run rerun the script as a sub process.  

But thinking about this,  I think `jira` assumes the `script` is for /bin/sh and might exec to that which I assume is not present on windows.

**Comment by rattboi** [comment]
I'm under git bash and cygwin, so I definitely have sh in my path. I'd be
surprised if it needed to be /bin/sh exactly. Also, I looked at go's
syscall.exec code and under windows it just returns EWINDOWS, which says
'not supported under windows'.

**Comment by coryb** [comment]
heh, okay that is pretty definitive :)  I will get a patch out soon to try os.exec on windows

**Comment by coryb** [comment]
I have updated kingpeon and tweaked how `jira` runs to just run a subprocess instead of system exec call, please try it out:
https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.4

If that does not work I will blow off the dust on my windows laptop and test it out this weekend.

**Comment by rattboi** [comment]
I can confirm it does now work under windows. I have only done the simplest test (the "jira mine" example), but it is now working in that case.

**Comment by coryb** [comment]
cool, thanks for the confirmation.
