### ISSUE TITLE
Question: How to update fields?

### ISSUE THREAD

**Issue by lbrigman124** [Netflix-Skunkworks/go-jira#117]
There is a need to update some field in an issue via the tool.  
Doing this via adding a comment works but with a very long issue, the comment could get buried.
Updating an individual field would allow the user to see the info at the top of the Jira issue.

This might already be possible with edit or editmeta but there isn't enough help details to figure it out for automation.

**Comment by coryb** [comment]
`jira` uses templates and allows you to override them for cases like this.  It it hard to come up with a generic template that makes everyone happy :) So the easiest thing to do is likely create a new template that matches your needs.   If you want to modify the template for the `edit` command you would do something like:
```
$ jira export-templates -t edit
$ cp $HOME/.jira.d/templates/edit $HOME/.jira.d/templates/custom-edit
```
Then modify `$HOME/.jira.d/templates/custom-edit` to match what you want and to use that template you would do:
```
jira edit -t custom-edit
```
More details can be read here: https://github.com/Netflix-Skunkworks/go-jira#templates

**Comment by lbrigman124** [comment]
So how would you set the custom_field with a template and --noedit option?

**Comment by coryb** [comment]
The  result of the template is always what is submitted.  If the `--noedit` option is provided we still process the template with data provided on the command line (like `--comment` or `--override`), so you would need to modify that template and allow an override to set to be used with `--noedit`

So if you wanted to allow a `--override myname=myvalue` option to set your `custom_field` then you would add something something like this to the edit template:
```
{{- if .meta.fields.custom_field}}
  custom_field: {{ if .overrides.myname }}{{.overrides.myname}}{{end}}
{{- end}}
```
