### ISSUE TITLE
The issuetypes command no longer works

### ISSUE THREAD

**Issue by gvol** [Netflix-Skunkworks/go-jira#119]
I'm trying to upgrade (the new custom command functionality is awesome!), but the issuetypes command no longer works.  It simply prints nothing.  I can send more verbose output, but it's very large.  Here's the most verbose non-huge output

```
$ ~/go/bin/jira issuetypes --verbose --verbose
DEBUG GET https://jira.corp.adobe.com/rest/api/2/issue/createmeta?projectKeys=AN&expand=projects.issuetypes.fields
$ j issuetypes --verbose --
2017-10-06T16:07:47.593-06:00 INFO  [cli.go:194] GET https://jira.corp.adobe.com/rest/api/2/issue/createmeta?projectKeys=AN
Xxx:          X xxxxxxx xxxxx xxxxxxx xx xxxxxxxx xxx xxxxxxxxx xx xxx xxxxxxx.
Xxxx:         xx.xxxxx.xxxx.xxxx
Xxxx:
Xxxxxxx:
Xxxxx:        xx.xxxxx.xxxxx.xxxx
Xxxx:         Xxxx Xxxxx Xxxx xx xxxx xx xxxxxx Xxxxxx Xxxx xxxxxx Xxxx.
Xxx-xxxx:     Xxx xxx-xxxx xx xxx xxxxx
Xxxxxx:
```

Because the new version is expanding fields, the returned JSON is much larger (and chunked).  Could that be the problem?

**Comment by gvol** [comment]
In what I think is a related issue, .meta is very small in templates.  In particular, it doesn't have any fields (and hence no allowedValues).

**Comment by coryb** [comment]
It is possible you have a custom template in `$HOME/.jira.d/templates/issuetypes`?  It seems to work for me against our testing service `go-jira.atlassian.net`:

```
$ jira issuetypes --project BASIC
Improvement:  An improvement or enhancement to an existing feature or task.
Task:         A task that needs to be done.
Sub-task:     The sub-task of the issue
New Feature:  A new feature of the product, which has yet to be developed.
Bug:          jira.translation.issuetype.bug.name.desc
Epic:         A big user story that needs to be broken down. Created by JIRA Software - do not edit or delete.
```

**Comment by gvol** [comment]
Man, you are amazing!  That was it.
