### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by oren** [Netflix-Skunkworks/go-jira#12]
my company is using the cloud version of jira. our url is: https://my-company.atlassian.net
so have a single line in config.yml:

```
endpoint: https://my-company.atlassian.net
```

```
jira ls -u=my-name -p=my-project

ERROR [cli.go:163] response status: 400 Bad Request
ERROR [util.go:196] Field 'resolution' does not exist or this field cannot be viewed by anonymous users.
ERROR [util.go:196] The value '=SANGRE' does not exist for the field 'project'.
ERROR [util.go:196] Not able to sort using field 'priority'.
```

any idea what could it be? Also, I couldn't find a password arguments in the --help or the readme.

Thanks!

**Comment by coryb** [comment]
Current go-jira only uses http basic authentication, which I believe does not work with the hosted jira from atlassian.  So I suspect you are not authenticated correctly and the query is working against public/unauthenticated credentials where almost nothing is available (ie the missing resolution field and unknown project).  

Do you know how the authentication works for your hosted jira? (using google oauth or something else?)

There is currently no password argument, go-jira will prompt you for a password when it get an gets an auth error from jira, or you can force it with `go-jira login`

-Cory

**Comment by oren** [comment]
thanks for looking into this. i don't know how the auth for the cloud version of jira works. when i'll have time to investigate i'll update this issue.

**Comment by coryb** [comment]
I have been trying to authenticate with the public https://jira.atlassian.com and have been seeing issues there also.  I am getting this header in the response:
`X-Authentication-Denied-Reason: CAPTCHA_CHALLENGE; login-url=https://jira.atlassian.com/login.jsp` 

I think this means that jira does not trust my client and assumes it is a bot (which is not terribly far from the truth) so it wants me to log in via a captcha-challenge.  I am not sure if there is something my client can do to make the auth attempt more trustworthy.  I will ping some people and see if I can get more information.

-Cory

**Comment by coryb** [comment]
I have tweaked go-jira to add a bit more debug output for login failures. 

You could see the raw response from jira if you run `jira login -v -v -v`

You will need the latest version available here: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/0.0.12

-Cory

**Comment by oschrenk** [comment]
Similar issue. I;m also using the cloud version.

I can view  a single issue without problems, but listing doesn't work

```
jira ls -p ELM -a oschrenk
2015-10-06T15:50:11.575+02:00 ERROR [cli.go:163] response status: 400 Bad Request
2015-10-06T15:50:11.575+02:00 ERROR [util.go:196] Not able to sort using field 'priority'.
```

I don't think it is an authentication issue. I rather think is an issue with which fields are being used in your workflow or not. I'm not an Jira expert but I don't think our company has priority defined, so the query issued by go-jira fails.

Maybe this is helpful? https://jira.atlassian.com/browse/JRA-30093 ?

**Comment by oschrenk** [comment]
It is indeed an issue with fields being used or not. I removed the default field `priority` in my branch and it works for our workflow, see https://github.com/oschrenk/go-jira/commit/57123862a4c4b326b8b33830aa22bd34c00a4974

**Comment by coryb** [comment]
@oschrenk thanks, jira is frustrating with the error messages we get back.  It could be related, but I am not sure how `resolution` is being put in the request from @oren, but his error message says "cannot be viewed by anonymous users" which I think means he is not authentiated correctly.  `priority` is being put in the request as the default sort order as you noted, if your project does not use priority you can easily change that in your `~/.jira.d/config.yml` file with:
```
sort: created
```

or with `jira --sort created ...`

**Comment by astrostl** [comment]
```
2016-11-15T15:15:31.727-06:00 ERROR [cli.go:231] response status: 400 Bad Request
2016-11-15T15:15:31.727-06:00 ERROR [util.go:234] Field 'resolution' does not exist or this field cannot be viewed by anonymous users.
2016-11-15T15:15:31.727-06:00 ERROR [util.go:234] The value 'LTF' does not exist for the field 'project'.
2016-11-15T15:15:31.727-06:00 ERROR [util.go:234] Field 'assignee' does not exist or this field cannot be viewed by anonymous users.
2016-11-15T15:15:31.727-06:00 ERROR [util.go:234] Field 'issuetype' does not exist or this field cannot be viewed by anonymous users.
2016-11-15T15:15:31.727-06:00 ERROR [util.go:234] Not able to sort using field 'priority'.
```

go-jira was humming along fine for me for months, but this just started up. Compiling the latest GitHub build hasn't resolved, nor has dropping fields (eventually you get down to required ones). Any general ideas?

**Comment by coryb** [comment]
@astrostl this can sometimes be caused by you not being logged in. The fields available to view are sometimes dependent on the user viewing, and jira will not always require re-authentication.  Try to `jira login` first and see if that resolves the issue.

-Cory

**Comment by astrostl** [comment]
Yeah, I've cycled and verified that. Running with `-v -v -v` I get `2016-11-15T15:23:16.716-06:00 DEBUG [cli.go:243] Response: HTTP/1.1 200 OK`, and it returns JSON with stuff like my total number of logins.

**Comment by astrostl** [comment]
Also blew away my whole `~/.jira.d` directory, logged in again (manual endpoint and user), and tried a `jira ls` with endpoint and project:

```
2016-11-15T15:26:54.940-06:00 ERROR [cli.go:231] response status: 400 Bad Request
2016-11-15T15:26:54.940-06:00 ERROR [util.go:234] Field 'resolution' does not exist or this field cannot be viewed by anonymous users.
2016-11-15T15:26:54.940-06:00 ERROR [util.go:234] The value 'LTF' does not exist for the field 'project'.
2016-11-15T15:26:54.940-06:00 ERROR [util.go:234] Not able to sort using field 'priority'.
```

I can see the cookie file in the newly-created directory.

**Comment by coryb** [comment]
Hmm, perhaps something changed on the server side?  Did the authentication method change?  The original error clearly says `anonymous users` so the jira service does not know who you are.  We have not changed anything in go-jira for this, so it seems like there is something wrong with your account on your jira server or the way authentication works has changed recently on the service.
-Cory

**Comment by astrostl** [comment]
That's my instinct, that something has changed API-side. I appear to auth and receive a cookie just fine, though.

**Comment by astrostl** [comment]
Noting: the JIRA "server" I'm using is Atlassian's own JIRA cloud.

**Comment by coryb** [comment]
I have never used the Atlassian cloud project (I use on-prem Jira) so I don't have much advice at the moment.  I am trying to create a new cloud jira and will try to do some testing.
-Cory

**Comment by astrostl** [comment]
I wonder if they couldn't be convinced to give a free developer testing account. Will try reaching out to them.

**Comment by astrostl** [comment]
`Request #CA-148243 confirmed: Purchasing and licensing request`

**Comment by coryb** [comment]
I created go-jira.atlassian.net to try the authentication and I was able to authenticate with the service for 1 request, but the cookie based authentication go-jira uses seems to be disabled on the service.  Valid cookies are presented but seem to be ignored by the server.

From my limited experimentation I suspect it has to do with "websudo" being enabled for the jira cloud product:
https://confluence.atlassian.com/adminjiraserver071/configuring-secure-administrator-sessions-802593160.html#Configuringsecureadministratorsessions-Disablingsecureadministratorsessions

When I ran jira locally for testing, I had to disable that for persistent cookie based auth to work.  For go-jira to work with this restriction I think we would have to force basic-auth on every request and would require users to put credentials in a config file or the environment (neither are very secure options).

-Cory

**Comment by astrostl** [comment]
I think that's a risk that can be locally managed, especially when the alternative is using the horrible JIRA web user interface :P We do have cookies stored locally, and most are probably not taking care to keep credentials out of their history file. A promising Mac and Linux option is https://github.com/sorah/envchain

**Comment by coryb** [comment]
Well, there is a big difference between getting access to a cookie for a specific service that will auto-expire within days vs getting access to the users raw password (which is probably shared across multiple services).  I think the keychain idea is a good one, the envchain is interesting but a golang library I think would be better.  I found this one that looks promising:  https://github.com/tmc/keyring  It has no windows support but we can probably fallback to cookie based auth or environment variables for windows.

**Comment by astrostl** [comment]
https://www.atlassian.com/software/views/open-source-license-request

**Comment by astrostl** [comment]
I began to fill it out for the project, but there are some specific details that I don't have.

**Comment by coryb** [comment]
I filled in the application, thanks I have been meaning to do that.
```
Thank you for your open source license application. 

Please allow ten to fourteen days for your open source license application to be processed. We'll be in touch via email.
```
Hopefully they can make https://go-jira.atlassian.net open and free for the project to use.
-Cory

**Comment by astrostl** [comment]
Local-security-risk workaround tested by a coworker: store auth in the `endpoint:` in `config.yml`. I had to urlencode the `@` symbol in my username (an email address) to `%40`.

`endpoint: https://EMAIL%40DOMAIN.COM:PASSWORD@ACCOUNT.atlassian.net/`

**Comment by coryb** [comment]
I have added some documentation for authentication strategies with `go-jira`, so I think this issue is finally solved by one of the methods:
https://github.com/Netflix-Skunkworks/go-jira/blob/master/README.md#authentication
