### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by gvol** [Netflix-Skunkworks/go-jira#120]
While trying to debug some problems I've been having, I've tried to build from source, but haven't succeeded. It would be nice to have some instructions in the readme.

**Comment by coryb** [comment]
Hey, there are some build instructions here:
https://github.com/Netflix-Skunkworks/go-jira#build

It just uses standard golang build instructions.

**Comment by gvol** [comment]
So I built and installed using that but IIUC that doesn't build the local repo with my changes.  There's a Makefile, so I tried typing make, but it failed.

I've never built go code before, so I guess I'll have to figure out how it works.

**Comment by coryb** [comment]
I see, yeah, golang does not really work that way, you cannot just git clone a repo and build it, you have to specifically git clone it to the "right" location in a GOPATH.  I used to fight against it now I have given up, too much stuff requires your go code to be in a $GOPATH.  

So this:
```
go get gopkg.in/Netflix-Skunkworks/go-jira.v1/cmd/jira
```
Will put the git repo in `$GOPATH` (defaults to `$HOME/go`) at `$GOPATH/src/gopkg.in/Netflix-Skunkworks/go-jira.v1`.  Once `go get` is run that directory should be the entire git repo with a corresponding `.git` directory.  To make modifications to the project you should work in that directory tree.  You may want to `git config --edit` to point to a private fork/branch.

**Comment by gvol** [comment]
Ah, very good.  Thank you.  A note to that effect in the README would have saved me some trouble.  I suspect others with no golang background will have similar issues.  For example, everyone on my team that I'm going to convince to use go-jira because it rocks!

**Comment by fentie** [comment]
@gvol If you have no go background when starting this, you can now use `brew install go-jira` as of today.

**Comment by catskul** [comment]
Is this recently merged pull request good enough to close this ticket? :

https://github.com/Netflix-Skunkworks/go-jira/pull/151

**Comment by gvol** [comment]
Looks great.  Thank you!
