### ISSUE TITLE
Unable to override resolution

### ISSUE THREAD

**Issue by gvol** [Netflix-Skunkworks/go-jira#121]
No matter what I do, `.overrides.resolution` seems to always be Done.  I tried passing`-o resolution=XXX` and `-o defaultResolution=XXX`, but to no avail.  It seems that around https://github.com/Netflix-Skunkworks/go-jira/blob/master/jiracmd/transition.go#L112 a `--resolution` flag is queried, but trying to use that with a transition command gives an error.  Then when it's not found it goes to the default which turns out to be "Done" for the Jira instance I'm using.

**Comment by coryb** [comment]
I am not sure about this one.  Jira requires a resolution, so I know we try to pick a reasonable default, but you should be able to explicitly define it.  I will try to figure out what is wrong.

**Comment by gvol** [comment]
@coryb, Does this PR look okay?

**Comment by coryb** [comment]
Hey, sorry missed your update, it has been merged.  Thanks!
