### ISSUE TITLE
Unable to set issuetype for subtask

### ISSUE THREAD

**Issue by lied** [Netflix-Skunkworks/go-jira#125]
I'm trying to setup a subtask with

`jira subtask ABC-1234` this gaves me

> ERROR Invalid Usage: Project ABC and IssueType Sub-task not found 

Our "Sub Task" issuetype is called Sub-Task. I tried the following which didn't work for me:
- jira subtask --override issuetype=Sub-Task
- set `issuetype: \n name: "Sub-Task"` in ~/.jira.d/templates/subtask
- set `issuetype: 'Sub-Task'` in ~/.jira.d/subtask.yml

How can I override the default `Sub-task` to be named `Sub-Task`?

**Comment by coryb** [comment]
Hey, you can override via a config file currently.  If you create `$HOME/.jira.d/subtask.yml` with the contents of:
```
issuetype: Sub-Task
```
it should work.

**Comment by coryb** [comment]
Oh, duh, you indicated that the ~/.jira.d/subtask.yml didnt work for you, not sure why it would not work ... I will see if I can reproduce.

**Comment by coryb** [comment]
Doh, found an issue that was causing the `Sub-task` default to take priority over the `.jira.d/subtask.yml` file, it has been fixed in code.

**Comment by coryb** [comment]
Fix released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.13

**Comment by lied** [comment]
Thanks! I already reconfigured the Subtask-Name in all our projects but I think the fix is also welcome by others. ;-)
