### ISSUE TITLE
unixproxy and socksproxy are used before config files are parsed

### ISSUE THREAD

**Issue by onionjake** [Netflix-Skunkworks/go-jira#131]
Right now you can't configure unixproxy or socksproxy in the yaml files because they are used before the config files are loaded.

**Comment by coryb** [comment]
Weird, I thought this used to work.  I confirmed what you are seeing, I will try to figure out how to fix this.  Thanks!
-Cory

**Comment by coryb** [comment]
Fixed and released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.14
