### ISSUE TITLE
Running from terminal results in error

### ISSUE THREAD

**Issue by Torbilicious** [Netflix-Skunkworks/go-jira#132]
Hi!
 When running from terminal i get `ERROR Post /rest/auth/1/session: unsupported protocol scheme ""`.

When running from my IDE(Intellij) everything works fine.

OS: macOS 10.12.6

I'd be glad to provide additional information if necessary

**Comment by coryb** [comment]
What is your endpoint configuration in `.jira.d/config.yml`?  It should be something like this:
```
endpoint: https://go-jira.atlassian.net
```

I suspect you are missing the scheme from the endpoint?

**Comment by Torbilicious** [comment]
I was able to get it working by copying the bundled config yaml to my home folder. Sadly in the progress i have overwritten the falty config. In both configs i had `http://insektarium.steinberg-intra.net`

**Comment by Torbilicious** [comment]
Ah i still had a copy open in my editor and it seems that for the falty file i put `yaml` and not `yml` as the file extension.

**Comment by dkushner** [comment]
I am still encountering this issue with only the following in my config:

```yaml
endpoint: https://mydomain.atlassian.net
login: dkushner@mycompany.com
```

**Comment by brandt** [comment]
In my case, the problem was that I was using the wrong extension for the config file:

Bad: `config.yaml`
Good: `config.yml`
