### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by ecoutu** [Netflix-Skunkworks/go-jira#133]
It would be amazing to have completion for bash and/or zsh.

**Comment by coryb** [comment]
We use the "kingpin" golang command line library which supports bash/zsh shell completion automatically: 
https://github.com/alecthomas/kingpin/tree/v2.2.5#bashzsh-shell-completion

**Comment by ecoutu** [comment]
Amazing! Maybe adding a mention in the README? I did search through the project + issues on github as well as a quick google and nothing obvious came up.

**Comment by coryb** [comment]
Yeah, will leave this issue open until I update the docs.  Thanks.

**Comment by catskul** [comment]
https://github.com/Netflix-Skunkworks/go-jira/pull/153

**Comment by catskul** [comment]
@ecoutu does #153 resolve this enough to close?
