### ISSUE TITLE
`shellquote` function for escaping text in custom scripts

### ISSUE THREAD

**Issue by anthonyrisinger** [Netflix-Skunkworks/go-jira#139]
`{{ ... | printf "%q"}}` does not properly quote output for shell, so it's not very useful in the `script:` of custom commands. `regReplace` seems to work, but you have to remember to also add extra single quotes yourself else you get strange shell errors.

Maybe it's worth exposing a dedicated `shellquote` (or similar) function?

```yaml
    script: |
      cat <<'EOF'
      #### EXPECTED
      {{toJson args}}
      EOF
      echo '#### REGREPLACE
      ''{{toJson args | regReplace "'" "'\\''"}}'
      echo '#### PRINTF (unquoted)
      '{{toJson args | printf "%q"}}
      echo '#### PRINTF (quoted)
      '"{{toJson args | printf "%q"}}"
```

Ouput:

```console
$ bin/jira sync '$HOME.$$.sprint'\''t.yml{,2}'
#### EXPECTED
{
    "DOC": [
        "$HOME.$$.sprint't.yml",
        "$HOME.$$.sprint't.yml2"
    ]
}
#### REGREPLACE
{
    "DOC": [
        "$HOME.$$.sprint't.yml",
        "$HOME.$$.sprint't.yml2"
    ]
}
#### PRINTF (unquoted)
{
    "DOC": [
        "/Users/anthony.74569.sprint't.yml",
        "/Users/anthony.74569.sprint't.yml2"
    ]
}
#### PRINTF (quoted)
{n "DOC": [n "/Users/anthony.74569.sprintt.yml\",
        \"$HOME.$$.sprintt.yml2"n ]n}
```
It's hard to notice, but the `printf` variant actually only has one item in the list :-)

**Comment by coryb** [comment]
Okay, just added a toMinJson function to remove the pretty-print, also added shellquote function that takes a string and quotes it.

So given this example:
```
custom-commands:
  - name: test-quote
    args:
      - name: DOC
        repeat: true
    script: |
      cat <<'EOF'
      #### EXPECTED
      {{args | toMinJson}}
      EOF

      cat <<'EOF'
      #### SHELLQUOTE
      {{args | toMinJson | shellquote}}
      EOF

      echo "#### ECHO RAW"
      echo {{args | toMinJson}}

      echo "#### ECHO SHELLQUOTE"
      echo {{args | toMinJson | shellquote}}```
This is the output I get:
```
$ ./jira test-quote '$HOME.$$.sprint'\''t.yml' '$HOME.$$.sprint'\''t.yml2'
#### EXPECTED
{"DOC":["$HOME.$$.sprint't.yml","$HOME.$$.sprint't.yml2"]}
#### SHELLQUOTE
\{\"DOC\":\[\"\$HOME.\$\$.sprint\'t.yml\",\"\$HOME.\$\$.sprint\'t.yml2\"]}
#### ECHO RAW
DOC:[/Users/cbennett.32161.sprint't.yml /Users/cbennett.32161.sprint't.yml2]
#### ECHO SHELLQUOTE
{"DOC":["$HOME.$$.sprint't.yml","$HOME.$$.sprint't.yml2"]}
```

**Comment by anthonyrisinger** [comment]
You sir, are a saint and a scholar. Many thanks!
