### ISSUE TITLE
How change custom field value

### ISSUE THREAD

**Issue by teopost** [Netflix-Skunkworks/go-jira#140]
Hello,
   I have to change the value of a custom field.

I tried this way:

`jira edit -o "customfield_10804=Deployed" AK-14930 `

But it does not work.

It can be done ?

**Comment by coryb** [comment]
Hey, what is sent to the Jira service is determined by the `edit` template.  So the overrides will only override a value in the template, if the value is not used in the template then it is not passed to Jira.
There is some information on template here:
https://github.com/Netflix-Skunkworks/go-jira/blob/master/README.md#templates

Basically you can export the `edit` template:
```
$ jira export-templates -t edit
NOTICE Creating $HOME/.jira.d/templates/edit
```
The modify the `$HOME/.jira.d/templates/edit` to add something like:
```
customfield_10804: {{ .overrides. customfield_10804 }}
```

The format in the template might require more formatting, depends on the field type.  You can get more information with `jira editmeta $ISSUE`

After the template has been modified then `jira edit ...` will by default use your template and you should see your customizations in your editor.

**Comment by hagna** [comment]
On a related note, if customfield_10804 is "select" how do you know which of the allowedValues is selected?

**Comment by coryb** [comment]
@hagna when processing the templates there is a `.meta` property which is the issue edit metadata.  That includes the `allowedValues` for properties that have restricted values.  You can see all the edit metadata with `jira editmeta ISSUE-123`.   The current `edit` templates utilize it for the `priority` field like:
```
  priority: # Values: {{ range .meta.fields.priority.allowedValues }}{{.name}}, {{end}}
    name: {{ or .overrides.priority ""}}{{end}}
```
This will print a list of `# Values: Major, Minor, etc` by looping over all the allowedValues for the `priority` property.
