### ISSUE TITLE
http errors and responseError

### ISSUE THREAD

**Issue by shendaras** [Netflix-Skunkworks/go-jira#141]
Currently, in `responseError`  the `http.Response` body is decoded into a `jiradata.ErrorCollection{}`.  For some errors, like 401 Unauthorized, this results in a JSON parse failure because the response body is not a JSON object.  

The error that is returned contains the parse failure but there's no way to determine the `StatusCode` or `Status` of the response.  I can guess at the failure by checking to see if the error returned is a `jiradata.ErrorCollection` and assuming the error is a non-200 response, but it would be nice to have a way to check more explicitly for the `Status`.

**Comment by coryb** [comment]
Hey, I just committed a change that should address this issue.  We now set the `Status` always and append to ErrorMessages if there is a json parse error.
