### ISSUE TITLE
AuthParams does not satisfy AuthProvider

### ISSUE THREAD

**Issue by djui** [Netflix-Skunkworks/go-jira#145]
I assume this is just an oversight, as `AuthOptions.AuthParams()` should be called `AuthOptions.ProvideAuthParams()`:  https://github.com/Netflix-Skunkworks/go-jira/blob/20a9666fcd408e4b804f017ca440c51ffb5eb10c/session.go#L20

**Comment by coryb** [comment]
Interesting, yes.  It looks like I dont actually use that struct anywhere.  I will fix, thanks!
-
