### ISSUE TITLE
worklog category

### ISSUE THREAD

**Issue by Maratyz** [Netflix-Skunkworks/go-jira#146]
Thanks for building this nice CLI tool. Is it possible to add worklog category for both worklog add and list subcommands?

**Comment by coryb** [comment]
What would a `worklog category` command do?  I didn't see any corresponding API for it:
https://docs.atlassian.com/jira/REST/server/

**Comment by Maratyz** [comment]
Hi Coryb, thanks for your reply and check over the Jira REST API. It is a custom field. So I think it does not benefit others too much. I will just close the request.
