### ISSUE TITLE
Cookie-based and basic auth with password to be deprecated on Jira cloud APIs - start using API tokens 

### ISSUE THREAD

**Issue by mansilladev** [Netflix-Skunkworks/go-jira#147]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for **cookie-based authentication** and **passwords in HTTP basic auth** requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by coryb** [comment]
Thanks for the heads-up, I will try to update the project soon.

**Comment by coryb** [comment]
This should work now. I have updated the docs for how to use api-tokens:
https://github.com/Netflix-Skunkworks/go-jira#authentication

**Comment by coryb** [comment]
released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.15
