### ISSUE TITLE
Login with API token returns 401 

### ISSUE THREAD

**Issue by catskul** [Netflix-Skunkworks/go-jira#148]
Using API token since I otherwise have 2FA enabled, and it does not appear to work.

Same credentials do work via jira-cmd.js project.

(Have tried normal password and also doesn't work)

```
? Jira Password [REDACTED@REDACTED.com]:  ****....***********
DEBUG POST https://REDACTED.atlassian.net/rest/auth/1/session
DEBUG Request: POST /rest/auth/1/session HTTP/1.1
Host: REDACTED.atlassian.net
Content-Type: application/json

{"password":"REDACTED","username":"REDACTED@REDACTED.com"}
DEBUG Cookie: atlassian.xsrf.token=REDACTED|REDACTED|lout; jsd.portal.language.anonymous=en-UK
DEBUG Response: HTTP/2.0 401 Unauthorized
Connection: close
Atl-Vtm-Backend-Time: 321
Atl-Vtm-Queue-Time: 0
Atl-Vtm-Time: 328
Cache-Control: no-cache, no-store, no-transform
Content-Type: application/json;charset=UTF-8
Date: Wed, 07 Mar 2018 02:31:06 GMT
Server: Atlassian Proxy/0.1.195
Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
Www-Authenticate: JIRA REST POST
Www-Authenticate: OAuth realm="https%3A%2F%REDACTED.atlassian.net"
X-Arequestid: REDACTED
X-Ausername: anonymous
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

{"errorMessages":["You are not authenticated. Authentication required to perform this operation."],"errors":{}}
```

**Comment by coryb** [comment]
Yeah, it looks like the api tokens don't work with the `/rest/auth/1/session` endpoint go-jira uses, I will have to update it.

**Comment by coryb** [comment]
A super hacky way to get around this is to just embed it in the basic auth for the endpoint so:

```
endpoint: https://user%40domain.org:<api-token>@domain.atlassian.net
```
Where the %40 is the uri encoding of `@` for the user email address.

**Comment by catskul** [comment]
I can confirm that the work around does work, but If I can help it I'd like to avoid leaving my API key in the config text file for the expected reasons.

I'd offer to put in the work to make the change myself, but I have 0 experience with go so would probably be an empty offer : /

**Comment by coryb** [comment]
Yeah, that is an insecure gross hack, I am trying to come up with something better, but will probably take a few days.

**Comment by coryb** [comment]
I do have some code for this working but I am trying to sort out integration test issues now (api keys for go-jira.atlassian.net dont seem to work for my test users, not sure why yet).

-Cory

**Comment by coryb** [comment]
This should work now.  I have updated the docs for how to use api-tokens:
https://github.com/Netflix-Skunkworks/go-jira#authentication

**Comment by coryb** [comment]
released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.15

**Comment by catskul** [comment]
Horray! Thanks!
