### ISSUE TITLE
Lacking instructions for local build of go-jira

### ISSUE THREAD

**Issue by catskul** [Netflix-Skunkworks/go-jira#149]
I'm trying to make local bug fixes, but the current build instructions appear to be for installing from remote source repositories.

Experimenting `go install` doesn't seem to work locally. 

I'm assuming `make` is the correct route, but is failing to build. I'm unsure if there's a problem or if I'm just doing it wrong, so have not filed a specific issue for that yet.

In any case, instructions for local build would be useful for those looking to contribute.

**Comment by catskul** [comment]
Figured it out. I'll make a pull request with an attempt at such instructions

**Comment by catskul** [comment]
This is probably obvious for those more experienced with go, but might be useful for newbies like me.

**Comment by coryb** [comment]
closing, merged PR. Thanks!
