### ISSUE TITLE
Defining your own sub-commands?

### ISSUE THREAD

**Issue by oschrenk** [Netflix-Skunkworks/go-jira#15]
New to go and this templating thing. Is it possible to define your own subcommands?

I would love to have `jira sprint` to run `jira ls --query="sprint in openSprints() and project=ACME"`

I tried to go with something like 

```
case $JIRA_OPERATION in
  sprint)
    echo "wohoo"
    ;;
  list)
    echo "template: table"
    ;;
esac
```

but that fails.

**Comment by coryb** [comment]
Yup, you can do that, it shoud look something like this:
```
case $JIRA_OPERATION in
  sprint)
    echo "command: list"
    echo "query: sprint in openSprints() and project=ACME"
    echo "template: table"
    ;;
  list)
   echo "template: table"
   ;;
esac
```

You needed to set the "command" property to that the internal `go-jira` command would be.

I have also use an ego command so show me everything open and assigned to me:
```
case $JIRA_OPERATION in
  mine)
    echo "command: list"
    echo "query: status not in ('CLOSED', 'RESOLVED') and assignee=$USER ORDER BY priority asc, created"
    echo "template: table"
    ;;;
esac
```

**Comment by oschrenk** [comment]
Awesome! Exactly what I needed!
