### ISSUE TITLE
tig like interface?

### ISSUE THREAD

**Issue by rodlogic** [Netflix-Skunkworks/go-jira#156]
I find [tig](https://jonas.github.io/tig/) quite useful for specific explorations on git. I am wondering if such an interface could be a next enhancement for this project. I.e. launch the console UI with a standard activities (or any other query) table and allow an easy navigation and interaction with the issues, further filtering, etc. The issues and other related data could be specifically cached for the duration of the interface and refreshed based on a keyboard command.

**Comment by mikepea** [comment]
I've built one already :)

https://github.com/mikepea/go-jira-ui

It needs a little bit of love (and updating to use go-jira.v1), but is
pretty functional. Let me know what you think!

**Comment by ydewit** [comment]
@mikepea Aha! Let me give it a shot.

**Comment by coryb** [comment]
I am not planning on any curses interface for go-jira.  I recommend @mikepea's project listed previously for a curses based interface.

**Comment by itai-stratoscale** [comment]
you could also try using fzf. for example:

jira list --query "resolution = unresolved and assignee=currentuser() ORDER BY created" | fzf --preview="echo {}| cut -d : -f 1 |xargs -I % sh -c 'jira view %'"
