### ISSUE TITLE
Configure the path where to store the password if using pass

### ISSUE THREAD

**Issue by gfa** [Netflix-Skunkworks/go-jira#157]
Hello

Great tool, however I use a company wide pass repo (and sub repos for personal/team/etc), therefore I don't want to write this password at the root of the repo.

I hack my way using .git/info/exclude to exclude the GoJira directory. 
I think it would be cool to be able to configure the path where to store the GoJira directory

that's it, thanks again for the tool :)

**Comment by coryb** [comment]
`jira` will merge configs in any parent directory, so maybe you can just put the configs in the `$HOME/.jira.d/config.yml` file?
https://github.com/Netflix-Skunkworks/go-jira#configuration

**Comment by gfa** [comment]
reading my previous report i realize it wasn't very clear, sorry abt that.

what i meant to ask is to have a configuration option to pass parameters to `pass`, currently if i try to pass parameters to pass jira won't recognize them and throw 

```
WARNING Unknown password-source: pass www/external/jira
```

my config
```
password-source: 'pass www/external/jira'
```

**Comment by coryb** [comment]
Ahh, I see.  There is a `PASSWORD_STORE_DIR=/path/to/directory` environment variable, would that work for you?

**Comment by gfa** [comment]
not exactly as that defines the base-path of the `pass` repo, 
I already setup that variable since I dont use ~/.password-store as the location for my pass repo.

I could wrap the jira command and set PASSWORD_STORE_DIR specially for jira as a workaround

anyway, this is not a big issue and there are many workarounds for it. feel free to close it

**Comment by coryb** [comment]
I have added at `password-directory: /path/to/password-store` property you can add to your `.jira.d/config.yml` file.  It will go out in next release.

**Comment by gfa** [comment]
:) Thanks!
