### ISSUE TITLE
Request to log jira help to stdout

### ISSUE THREAD

**Issue by mbigras** [Netflix-Skunkworks/go-jira#158]
Thank you so much for this application! I use it every day and am very happy with it. I'm having an issue where I'm not able to quickly use the output of the help because it's being logged to standard error instead of standard out.

**Request**

Log jira help to standard out.

**Reasons why**

* It's hard to remember to redirect to standard out
* It's hard to type `2>&1` especially in the context of "quickly wanting to find help"
* Logging help to standard out follows some widely accepted [coding standards](https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html)

**Context**

Using jira to quickly find something on the help menu or prevent the help output from scrolling past the screen.

**Solution**

The solution to both those problems is to use `grep` or `less`.

For example, if I want to find the first custom command that has the `sse` prefix:

```
jira help | grep sse | awk NR==1
  sse-create:          Create issue AND add to the current sprint
```

This isn't possible right now because go-jira is sending the help to standard error.

**Current workaround**

Redirecting standard error to standard out

```
jira help 2>&1 | grep sse | awk NR==1
  sse-create:          Create issue AND add to the current sprint
```

**[GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.htm) link summary**

>4.7.2 --help
>The standard --help option should output brief documentation for how to invoke the program, on standard output, then exit successfully.

**Comment by coryb** [comment]
Released a fix for this: https://github.com/Netflix-Skunkworks/go-jira/releases/latest

**Comment by mbigras** [comment]
Thank you for taking the time to work on this @coryb! Greatly appreciated :)
