### ISSUE TITLE
Re-configure api token when using keyring

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#160]
I've ended up with a bad API token inside keyring that is no longer granted for usage.

How can I refresh the token and store a new one?

**Comment by coryb** [comment]
which keyring are you using?  Are you using the system keyring on osx or using `pass`?

**Comment by vanniktech** [comment]
Oh sorry. keyring on an Ubuntu machine. So that's probably `gnome-keyring`.

**Comment by coryb** [comment]
If you are using `pass`, then you can use:
```
pass rm --force GoJira/api-token:<user>
```
where `<user>` is the `user: ` property in the `.jira.d/config.yml` file (defaults to `$USER` environment variable).

If you are using your system keystore then there should be a key named `GoJira/...` in there that you can browse to and remove.

I will probably modify the `jira logout` command to make this easier.

**Comment by vanniktech** [comment]
Yeah I also tried `jira logout` but it said it's not necessary. Would be great to have an addition that would remove the key.

**Comment by vanniktech** [comment]
I've tried `seahorse` which seems to be the thing for looking up the `keyring` passwords. However there's a default password for it and I don't know what it is. Bottom line is that I can't access any of them so I can't delete it either.

**Comment by coryb** [comment]
I have never actually used gnome-keyring, apparently deleting a key is not easy:
https://blmath.wordpress.com/2009/07/07/remove-password-from-keyring/  that will delete *all* your keys, which is dumb.

I am trying to add in a prompt now to the logout command.

**Comment by vanniktech** [comment]
Yeah another solution I've read online is `rm ~/.local/share/keyrings` which is equally as bad. The prompt would be nice.

**Comment by vanniktech** [comment]
`go install ./` worked. Where can I find the executable? Sorry for the questions - never worked with Go before.

**Comment by coryb** [comment]
If you just want to install the binary:
```
go get -u gopkg.in/Netflix-Skunkworks/go-jira.v1/cmd/jira
```

That should install it to `$GOPATH/bin` which defaults to `$HOME/go/bin`

-Cory

**Comment by criffel** [comment]
Cory - Off topic but Thank you for this tool. Makes my life that much easier at work. JQL has unassigned equal to 'IS EMPTY' in query fields while trying to search for unassigned tickets... Has this already been thought of in your script? if so, how would I jira list -p project -a unassigned ?

Again, thank you!

**Comment by vanniktech** [comment]
I don't get the prompt when running `./jira logout`. Could it correlate to the failing master build?

**Comment by vanniktech** [comment]
I know for a fact that I'm running a different version since I'm now seeing this issue #163

**Comment by coryb** [comment]
Not sure what going on.  The tests failed on the build due to the prompt being added (test's dont expect that prompt) , but that wont effect your build.   I built it locally and it worked for me.

**Comment by vanniktech** [comment]
Could it be that `globals.GetPass()` is empty?

**Comment by coryb** [comment]
If that is the case then it implies your api-token has been flushed from the keychain and you should be good?

**Comment by vanniktech** [comment]
I _should_ be yes - but I'm not. I've also tried restarting, deleteting `~/go`, redownloading. Nothing seems to get that prompt to show.

**Comment by coryb** [comment]
Lets take a step back, when you run something like `jira list` do you get prompted for an api-token or does it just fail (and if so with what error message).

**Comment by vanniktech** [comment]
When I use `password-source: keyring` I don't get prompted for an access token. In this case executing `jira list` yields a 401.

When I don't use `password-source: keyring` I get prompoted for an access token. Once I enter the new valid one I see the issues.

**Comment by coryb** [comment]
Okay, I am pretty confused with what is going on.  In theory when you get the 401 we are supposed to prompt you again for another token to use, but that code may have been lost in a refactor.   I dont have time to really dig into this further, for now can you unset the `password-source` property and just set the `JIRA_API_TOKEN` environment variable?

**Comment by vanniktech** [comment]
I'll try this tomorrow as I'm no longer at my work computer where I had this problem.

Which exact property are you talking about when you're referring to `password-source`?

**Comment by coryb** [comment]
You said you have `password-source: keyring` set, I just meant to unset that and try the `JIRA_API_TOKEN` environment variable for now.

**Comment by vanniktech** [comment]
Oh yes, you're right. Got mixed up.

**Comment by vanniktech** [comment]
Whops. Using the environment variable works fabulously.

**Comment by coryb** [comment]
made some fixes, released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.17

**Comment by SijanC147** [comment]
Was this issue fixed, am still experiencing this. I entered the wrong API key by mistake the first time, and now if i include `password-source: keyring` it always fails. `jira logout` suggests that it's deleting something, but doesn't fix the issue the next time i run any command. Removing the keyring setting from config makes it ask for my token on every command. Am i missing something?
