### ISSUE TITLE
Jira assign yields OK but does nothing

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#164]
Executing `jira assgn ap-41` yields `OK ap-41 <url>/browse/api-41` however when checking online it does not actually assign me.

I've tried:

- `jira assign ap-41 "Niklas Baudy"` which is my full name and there I'm getting `Invalid Usage: assignee: User 'Niklas Baudy' does not exist.`
- Same for `jira assign ap-41 niklas.baudy@moovel.com`

Executing `jira assign ap-41 niklas.baudy` does the trick as apparently that's my user name.

I've ended up putting `assignee: niklas.baudy` into my yml configuration to make this work out of the box.

In any case the request should not respond with an OK when nothing has been changed.

**Comment by coryb** [comment]
Maybe this will work:
https://github.com/Netflix-Skunkworks/go-jira#user-vs-login

I think you need:
```
user: niklas.baudy
login: niklas.baudy@moovel.com
```

**Comment by vanniktech** [comment]
Ah that explains it. Thanks. Also I've seen that there is `jira take ap-41` to assign it to me so I won't need assign and can use it when assigning it to someone else.

I'll close this then.
