### ISSUE TITLE
Jira comment opens up editor for yml configuration when message was already provided

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#165]
Executing `jira comment ap-41 -m "Foo bar."` will open the editor where you can change the yml. However I find this step unnecessary since there are no more fields that I could specify. The only change I could do is edit the message.

Hence I'd propose to not show the editor and submit the comment straight away.

**Comment by coryb** [comment]
There is a `--noedit` option:
```
      --noedit             Disable opening the editor
```

That will bypass the editor and try to submit immediately.  Does this work for you?

**Comment by vanniktech** [comment]
From the name of it, it would yes. How could I configure this in conjunction with:

```bash
case $JIRA_OPERATION in
    comment)
        ;;
esac
```

**Comment by coryb** [comment]
```
case $JIRA_OPERATION in
    comment)
        echo "noedit: true"
        ;;
esac
```

You can also create a `.jira.d/comment.yml` with `noedit: true` in it so the config does not need to be executable.

**Comment by vanniktech** [comment]
Oh that's even better. Thanks :+1:
