### ISSUE TITLE
--template=FOO broken in v1 on absolute paths

### ISSUE THREAD

**Issue by jez** [Netflix-Skunkworks/go-jira#166]
Feeding an absolute path to the `--template` flag seems to not work.
I've reproduced this with the `jira create` subcommand, but from a
cursory scan of the code, I think it should affect all commands that
can customize the template.

In particular, this is problematic because

- the `mktemp` command returns an absolute path within `$TMPDIR`
- the `command1 <(command2)` shell syntax opens up a temporary file at
  `/dev/fd/12345` to capture the subshell output from `command2` and
  put into a file for `command1` to use.

So it's somewhat annoying to use temporary template files right now
(the temp file has to be in the same directory that you exec the
`jira` command).

I do not see this behavior on v0, only on v1.

#### [OK] Same directory

```bash
cd ~
touch ~/foo.yml
jira create -p MYPROJECT --template=foo.yml
```

- **Expected**: `$EDITOR` should open with our (empty) template
- **Actual**: `$EDITOR` opens (this case is working fine!)

#### [BAD] Relative path

```bash
cd ~
mkdir ~/my-folder
touch ~/my-folder/foo.yml
jira create -p MYPROJECT --template=my-folder/foo.yml
```

- **Expected**: `$EDITOR` should open with our (empty) template
- **Actual**: Fatal error:

    ```
    ERROR Invalid Usage: open /var/folders/b0/43zg3s114tb1rcdfflfftg7m0000gn/T/my-folder/foo.yml987543717: no such file or directory
    ```

#### [BAD] Absolute path

```bash
cd ~
touch ~/foo.yml
# Your shell will expand $HOME to an absolute path before exec'ing the command
jira create -p MYPROJECT --template=$HOME/foo.yml
```

- **Expected**: `$EDITOR` should open with our (empty) template
- **Actual**: Fatal error:

    ```
    ERROR Invalid Usage: open /var/folders/b0/43zg3s114tb1rcdfflfftg7m0000gn/T/Users/jez/foo.yml987543717: no such file or directory
    ```

**Comment by coryb** [comment]
Hey, thanks for the error report, I was able to reproduce, fixing now.

**Comment by coryb** [comment]
released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.17

**Comment by jez** [comment]
Just tried it out, and it works great now!

Thanks for the fast turnaround 🙂
