### ISSUE TITLE
Question: possible to add a global password flag

### ISSUE THREAD

**Issue by robtec** [Netflix-Skunkworks/go-jira#169]
Hi,  great CLI BTW 😄 

I'm using it on Windows (Cygwin) but the password prompt on `jira login` doesn't work, a cygwin bug reading input 😢, works fine in CMD.exe.

Locally I have added a `--password` global flag and  `GetPass()` uses that when present, would this be something you guys would like contributed back?

I understand its really not a bug but just said I would suggest it

Cheers
Rob

**Comment by coryb** [comment]
I will try to look into the cygwin bug, the prompts should work there.

Maybe you can use the `JIRA_API_TOKEN` environment variable?  It is briefly covered in the docs: https://github.com/Netflix-Skunkworks/go-jira#authentication

**Comment by robtec** [comment]
Cheers for the reply

Cygwin was giving an Invalid Handle error

I'm AFK right now but will look into the API Token and see if it works with our instance

Thanks again

**Comment by robtec** [comment]
Token worked fine :blush: cheers
