### ISSUE TITLE
jira-cli ls shows a list of ip addresses instead of jira IDs

### ISSUE THREAD

**Issue by AxelFooley** [Netflix-Skunkworks/go-jira#173]
As the title says:

`▶ jira-cli ls -q "project = PROD AND status = Resolved AND resolved >= -1d ORDER BY updated DESC"

10.178.134.179:7115
10.178.134.179:7131
10.178.134.197:7145
10.178.134.197:7147
10.178.134.245:7149
10.178.134.248:7105
10.178.134.248:7107
10.178.135.3:7117
10.178.135.3:7119
10.178.135.27:7141
10.178.135.27:7143
10.178.145.51:7129
10.178.176.112:7109
10.178.176.112:7125
10.192.58.21:7127
10.192.58.21:7133
10.192.58.21:7135`

What i'd like to have is instead the list of tickets in resolved state like "PROD-XXXX"

Version: jira-darwin-10.6-amd64

**Comment by coryb** [comment]
Is it possible you have a file named `list` in your current directory with the ip addresses in it?  This might be related to #167

**Comment by AxelFooley** [comment]
It's exactly my case!! i didn't know that file even existed on my laptop :D
Removing that file fixed, thanks a lot.

**Comment by coryb** [comment]
same as #167, closing duplicate
