### ISSUE TITLE
Move given ticket into the current sprint

### ISSUE THREAD

**Issue by vanniktech** [Netflix-Skunkworks/go-jira#174]
Is there any way to move a given ticket into the current sprint? e.g. `jira move sprint AP-123`

I could not find anything for it.

**Comment by coryb** [comment]
There is no easy way to do it, but you can create your own dynamic commands that will probably work, more information in #135

**Comment by vanniktech** [comment]
Oh wow that's really cool. Should we add this kind of custom command to the README as it demonstrates how to use the rest api with multiple calls?
