### ISSUE TITLE
Abort operation when no change or empty file after leaving editor

### ISSUE THREAD

**Issue by dummyhuan** [Netflix-Skunkworks/go-jira#188]
Hi, is it possible to support aborting operation if no content is changed, or empty content is saved after leaving editor when creating issues or doing similar operation, just like what `git commit` do. It don't feel good seeing below error:

```
[user@localhost app]# jira create
ERROR Internal server error
? Jira reported an error, edit again? No
```

Thanks for the work.

**Comment by coryb** [comment]
That is how `jira` works.  We do a diff of the input content vs the content we got back and if unchanged we prompt `No changes detected, submit anyway?`.  So it sounds like your editor is modifying the content by default (maybe reformatting and/or whitespace) so it looks like the document has been modified.
