### ISSUE TITLE
fixVersion override fails for transition

### ISSUE THREAD

**Issue by rilsmith** [Netflix-Skunkworks/go-jira#192]
[This change](https://github.com/Netflix-Skunkworks/go-jira/commit/5084524266c1c15c23730cf31c3d784d54d076f5) for [this issue](https://github.com/Netflix-Skunkworks/go-jira/issues/89) seems to cause an error if attempting to override fixVersions.

```
jira resolve -ofixVersions="fixVersion1,fixVersion2" <ISSUE>
ERROR template: gojira:26:14: executing "gojira" at <.name>: can't evaluate field name in type string
```

Shouldn't the fixVersions override for this template use `{.}` not `{.name}`?
`.name` makes sense if it's coming from the existing JIRA structure (i.e. line 508) but the override values array resulting from splitting by comma won't have `.name` so line 507 should reference `{.}` instead?
Or am I just using the fixVersions override incorrectly?

**Comment by coryb** [comment]
fixed in [latest release](https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.18)
