### ISSUE TITLE
Identify session invalidity

### ISSUE THREAD

**Issue by khmarbaise** [Netflix-Skunkworks/go-jira#196]
* Overview
Lets say I've worked a time with the command line client and than make a break ..
afterwards I use another command and I'm prompted with the password input...

* Suggestion
It would be great having a command which tell me that the session has expired and I need to do relogin (type i my password). This would be great for scripting to show the user an explicit message "you have to login".
this would prevent scripts from eating up the `password dialog` (`? Jira Password [username]:`)if the output has been redirected...

* Idea
go-jira session

* return code: 
  * 0 session is valid.
  * 1 session is invalid. Need to do login

Another idea would be to have an explicit return code in each command could tell me the same.

BTW: Really great tool very helpful.

**Comment by coryb** [comment]
You might want to use a tool  like `pass` to store your secrets in a gpg agent or system keychain, not sure if that would solve your problem (ie reduce or eliminate the password prompt all-together).

Maybe you can use `jira login` to authenticate with the service before moving on to your automation?

**Comment by khmarbaise** [comment]
The first sentence would be a solution..

The second is exactly what I like to prevent cause if someone runs a script which contains a command like `jira whatever ..` in particular if it is redirected for scripting the problem arises (the script would stop and based on the redirection you can't see the password prompt). At the moment I have no option/command to check if I need to do a `jira login` before I can continue..

Maybe it would be possible having a return code saying you are not logged in anymore you have to use `jira login` ...which could be handled in scripts.....

Maybe I misunderstand a thing...at the moment...nevertheless thanks for your answer...

**Comment by coryb** [comment]
Okay, this sort of functionality seems to be getting harder with Jira.  They are moving away from the cookie based sessions and moving towards requiring basic auth for every request, at least they have [dropped support](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/) for session based authentication on hosted atlassian.net services.

I assume you are using a locally hosted jira that still supports the `session` API?  I should be able to add a `jira session` command pretty easily to report current session details although I don't think I have any running services where I can test this (I use hosted atlassian.net for testing).

**Comment by coryb** [comment]
Added `jira session` command in [latest release](https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.18), hopefully it will work for your needs.

**Comment by khmarbaise** [comment]
Wow ...great...I will try within the next days..Thanks for your support..
