### ISSUE TITLE
cookies not longer sent to service

### ISSUE THREAD

**Issue by coryb** [Netflix-Skunkworks/go-jira#201]
@artem-nefedov opening a new issue.  It seems like `jira` is updating the cookies file but for some reason there are no cookies on the http request to the service. So the `Set-Cookie` functionality seems to be working and they are getting assigned to the "cookie jar", but no cookies are sent back to the service on subsequent requests. 

So I can reproduce this now, I didn't see it earlier because I use `pass` as the password manager, it was just resubmitting credentials automatically.

I will try to figure this out.

**Comment by coryb** [comment]
I have [released](https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.20) a new version that should work now.  There was a library that we use for dealing with cookies that was recently broken in an update. It has been fixed, so hopefully your cookies will be loaded and applied to requests to the jira service now.

**Comment by artem-nefedov** [comment]
Thanks. It is working correctly now.
