### ISSUE TITLE
default edit template is problematic

### ISSUE THREAD

**Issue by mikepea** [Netflix-Skunkworks/go-jira#23]
The standard permissions set on our Jira instance do not allow for update of `reporter`. I'm fairly confident this will be a commonplace limitation for unprivileged users.

This means that every 'edit' operation initially fails with:

    {"errorMessages":[],"errors":{"reporter":"Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown."}}

I appreciate that a custom edit template can be provided to remove this, but in my mind it makes more sense for the default edit template to fit a lower common denominator.

**Comment by coryb** [comment]
Closing this issue, the edit and create templates were modfied to only show reporter if it is a valid metadata field.

-Cory
