### ISSUE TITLE
Build instructions are wrong

### ISSUE THREAD

**Issue by ydgholz** [Netflix-Skunkworks/go-jira#36]
The simple build instructions say to run:

> git clone git@github.com:Netflix-Skunkworks/go-jira.git
> cd go-jira
> export GOPATH=$(pwd)
> export GOBIN=$GOPATH/bin
> export PATH=$GOBIN:$PATH
> cd src/github.com/Netflix-Skunkworks/go-jira
> go get -v

The second cd fails, as there's no `src` directory in the cloned repo.

**Comment by coryb** [comment]
Thanks, will update.

`make` will build it now, and put the binary at ./jira

-Cory
