### ISSUE TITLE
Dumping all (populated) fields for a given issue

### ISSUE THREAD

**Issue by astrostl** [Netflix-Skunkworks/go-jira#46]
Howdy,

Is there a mechanism to dump all fields for a given issue? `jira [ID]` or `jira view [ID]` only appear to show a sub-set. Populated-only would be ideal, but even showing everything would be helpful for debugging. The specific use-case here is that I have a story issue which I know to have an associated epic, and I can see from `jira fields` that there are several epic-related fields which are visible to go-jira.

Thanks!

**Comment by coryb** [comment]
You can see the raw response from jira with:
```
jira ID -t debug
```
The `debug` template is really just raw json output, so you will see the entire context that is passed to the templates.  This allows you to see all the data that is available to you when trying to write your own templates.

-Cory

**Comment by astrostl** [comment]
Feature req to get that added to CLI usage output?
I can see that `-t` is documented for templates, but calling out this use-case could be helpful.

**Comment by coryb** [comment]
Updated the README with some info on how to write/edit templates:

https://github.com/Netflix-Skunkworks/go-jira#writingediting-templates

-Cory
