### ISSUE TITLE
make install not working for me on Mac

### ISSUE THREAD

**Issue by astrostl** [Netflix-Skunkworks/go-jira#48]
Howdy,

`make clean && make` works as expected.

`make install` yields the following:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make GOBIN=~/bin build
go build -v -ldflags "-X jira.VERSION=0.1.3 -w -s" -o '~/bin/jira' main/main.go
command-line-arguments
```

but no binary in ~/bin/ . `./jira` works fine, though, and I can copy it over myself.

Could this be some kind of Go build env issue for my system?

**Comment by coryb** [comment]
doh, the Makefile was bogus, it was writing to the literal `~` directory because it was quoted and didnt allow shell expansion.  I just changed it to use the $HOME var explicitly.

**Comment by yqrashawn** [comment]
Still won't work on mac after changing to $HOME.

**Comment by yqrashawn** [comment]
```
src/github.com/Netflix-Skunkworks/go-jira/commands.go:7:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
        /usr/local/Cellar/go/1.6.3/libexec/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
        /Users/Rashawn/Downloads/go-jira-0.1.3/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
Makefile:49: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/Users/Rashawn/Downloads/go-jira-0.1.3'
Makefile:75: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by coryb** [comment]
@yqrashawn I think this is a different issue.  I think the initial `go get` probably failed via the Makefile, so if you `make clean` then `make install` I think it will work.

**Comment by yqrashawn** [comment]
@coryb thanks! It work! But I'm now facing a username problem.
```
jira --user=test          
2016-08-05T23:39:06.263+08:00 ERROR [main.go:313] Not enough arguments. 1 required, 0 provided
```

**Comment by coryb** [comment]
@yqrashawn  Uh, Im confused.  You are getting a usage error, nothing to do with user.  `jira --user=test` is not a valid command because you are not asking `jira` to do anything.  You want something like this to show details about an issue (fill in $ISSUE with a valid jira issue id)
```
jira --user test $ISSUE
```
Or to show all open issues for a project (fill in $PROJECT with a valid project name):
```
jira --user test --project $PROJECT list
```

**Comment by yqrashawn** [comment]
Oh, got it. The problem is I need to login first, and the `jira login` command only ask for password and use $USER as default username, but my user name on server is not. So how can I change the default username?

**Comment by coryb** [comment]
The documentation needs to be inproved, but this section covers coniguration:
https://github.com/Netflix-Skunkworks/go-jira/blob/master/README.md#configuration

So you would create `$HOME/.jira.d/config.yml` with contents something like:
```
endpoint: https://jira.mycompany.com
user: jira-user
```

Then login will hopefully work.

**Comment by yqrashawn** [comment]
@coryb Oh! Sorry to bother! Really thanks. I must be drank.

**Comment by yqrashawn** [comment]
@coryb I did't read the README.md carfuly. Sorry to bother.

**Comment by yqrashawn** [comment]
Uh, another question. I have to enter my password every time I request to the server. I put my password into config.yml but it doesn't work. So is there any way to solve this. Or is this the problem of the server?

**Comment by coryb** [comment]
If the error message says something about WebSudo then your jira server does not support the cookie based authentication which `go-jira` uses.  There is currently no support for adding a password into the config file so `go-jira` is ignoring that value currently.  I have created a separate issue for that: #50

**Comment by yqrashawn** [comment]
@coryb There's no error message, just asking me to enter password. I believe it's the server's problem as you said.
