### ISSUE TITLE
Missing package go-jira/data

### ISSUE THREAD

**Issue by dbrower** [Netflix-Skunkworks/go-jira#51]
I cloned a copy of the repo (tag is v0.1.4) and when running make I get a failure with the following message:

    src/github.com/Netflix-Skunkworks/go-jira/commands.go:8:2: cannot find package "github.com/Netflix-Skunkworks/go-jira/data"

It looks like the `data` subdirectory is missing from this repo.

**Comment by coryb** [comment]
Doh!  Thanks, I have added the directory.  The data directory is generated structs from the jira api json schemas that I am starting to use.

I will get go-jira building via Travis so I can avoid these dumb issues in the future.

-Cory
