### ISSUE TITLE
optionally show the full URL of the issue with the list command

### ISSUE THREAD

**Issue by mlbright** [Netflix-Skunkworks/go-jira#54]
On OSX, if you use iTerm2, the terminal will detect URLs. If doing a `jira list`, it would be nice to be able to click on a issue without having to issue another command.

I have this working with `jira -b list` here: https://github.com/mlbright/go-jira/tree/ls-urls. I can open a PR if this is something that you would entertain.

My golang-fu is not the greatest so I'm not sure I'm handling the data with type assertions properly, but it works.

**Comment by coryb** [comment]
Hey, if you only use a single jira service you can just create a custom template with your embedded hostname like his:
```
{{ range .issues }}https://jira/browse/{{ .key | append ":" | printf "%-12s"}} {{ .fields.summary }}
{{ end }}
```

Save that content to `~/.jira.d/templates/list` and that will be the default template used for the "list" command.  Or save it to `~/.jira.d/templates/list-url` and you can use it like `jira ls -t list-url`.

**Comment by mlbright** [comment]
Thanks!
