### ISSUE TITLE
any way to use go-jira by passing a user name?

### ISSUE THREAD

**Issue by perfecto25** [Netflix-Skunkworks/go-jira#55]
I can run gojira as whatever user Im logged in as on my linux box, and I can provide a password, 

is there a way to run it as a different JIRA user thats not the same as your OS user? Can I pass a username somewhere? 

Thanks.

**Comment by coryb** [comment]
You can use the `--user name` option (or set `user: name` in `.jira.d/config.yml`).  It is mentioned briefly in the usage:
```
General Options:
  -b --browse         Open your browser to the Jira issue
  -e --endpoint=URI   URI to use for jira
  -h --help           Show this usage
  -t --template=FILE  Template file to use for output/editing
  -u --user=USER      Username to use for authentication (default: $USER)
  -v --verbose        Increase output logging
```
-Cory

**Comment by perfecto25** [comment]
ahh, missed that. Thanks!
