### ISSUE TITLE
User password expiration

### ISSUE THREAD

**Issue by perfecto25** [Netflix-Skunkworks/go-jira#56]
is there a way to store a logged in users creds indefinitely?

Im lookign at cookies.js and it has an expiration date for the provided password. Can I increase this range?

**Comment by coryb** [comment]
The expiry on the cookie is a bit tangential to the expiry of the actually session token.  We set the expiry on the cookie to be 1 week, but actual session expiry is configured via the jira server (there is a web.xml with something like `<session-timeout>10080</session-timeout>` which is how long the session token is valid for.  I can tweak the cookie management code to extend that session timeout, but that would only work for the case where the `session-timeout` is configured to be longer than 1 week.

-Cory

**Comment by perfecto25** [comment]
Thanks Cory, got it working. This is fantastic product, saved us lots of sweat and cursing trying to do workflows via jira.
