### ISSUE TITLE
jira login does not ask for an account name just a password

### ISSUE THREAD

**Issue by MadBomber** [Netflix-Skunkworks/go-jira#57]
The documentation says to authenticate myself I do the command

  jira login

When I do all it asks for is a password.  Seems to me that if should ask for my account name before it asks for my password.

To bad I can't get past this initial configuration glitch.... other than that looks like a nice feature complete CLI tool.

**Comment by coryb** [comment]
it assumes your $USER environment variable matches your jira user name.  If this is not the case then set:
```
user: username
```
In the `$HOME/.jira.d/config.yml` file.

Then the jira commands, including `jira login` will use the correct authentication data.

-Cory

**Comment by astrostl** [comment]
Submitted a tiny PR to put this in the README
