### ISSUE TITLE
Moving tasks in structure

### ISSUE THREAD

**Issue by Mike-Now** [Netflix-Skunkworks/go-jira#59]
# Feature request

It would be nice to have the ability to move a task to a story or to another task as a subtask in structure. Currently that functionality is missing as far as I'm concerned.

**Comment by coryb** [comment]
Not opposed to this idea, but not sure what the interface would look like.  How would you envision the usage to be?

**Comment by Mike-Now** [comment]
The special action could be used to differentiate normal usage from the "structure" view.
The new actions in go-jira would therefore look something like this:

`jira structure move sub ISSUE ISSUE`
`jira structure ls`

etc.

**Comment by coryb** [comment]
Unfortunately it seems there is no programmatic way to move an issue in Jira:
https://jira.atlassian.com/browse/JRASERVER-16494
Closing this issue until Atlassian can provide an API for this.
