### ISSUE TITLE
if create template is not saved, consider the create aborted

### ISSUE THREAD

**Issue by jaybuff** [Netflix-Skunkworks/go-jira#6]
If I run "jira create" then do not save my changes, the client should not attempt to POST to jira or offer me the option to edit again.

Right now, I get this output after I do ":q!" in vi:

    2015-02-18T11:25:40.059-08:00 INFO  [cli.go:105] POST https://issues.apache.org/jira/rest/api/2/issue
    2015-02-18T11:25:40.111-08:00 ERROR [cli.go:158] response status: 400 Bad Request
    2015-02-18T11:25:40.111-08:00 ERROR [commands.go:290] Unexpected Response From POST:
    HTTP/1.1 400 Bad Request
    Connection: close
    Transfer-Encoding: chunked
    Cache-Control: no-cache, no-store, no-transform
    Content-Type: application/json;charset=UTF-8
    Date: Wed, 18 Feb 2015 19:25:37 GMT
    Server: Apache-Coyote/1.1
    X-Arequestid: 1165x16501598x2
    X-Asen: SEN-2062203
    X-Asessionid: 14tags9
    X-Ausername: jaybuff
    X-Content-Type-Options: nosniff
    X-Seraph-Loginreason: OK

    75
    {"errorMessages":[],"errors":{"project":"project is required","issuetype":"Could not find issuetype by id or name."}}
    0

    2015-02-18T11:25:40.111-08:00 ERROR [cli.go:303] Unexpected Response From POST
    edit again? [Y/n]: n

**Comment by coryb** [comment]
yeah, we can try this approach, it will not work with some editors that auto-save.

When I want to abort, I usually just add a bogus field:
abort: true

then when jira rejects the bogus message I say "n" to the prompt.  

-Cory

**Comment by coryb** [comment]
I now check to see if the file has been modified from the original presented to the editor and abort the operation if I detect no changes.  See (e69b65c)
