### ISSUE TITLE
jira add worklog + started time.

### ISSUE THREAD

**Issue by sylus** [Netflix-Skunkworks/go-jira#66]
Hi there! Again many thanks for this awesome tool!

I think I read this in a related issue that adding the 'started' doesn't work for `jira add worklog` and wasn't needed anymore? I found it is actually useful if you immediately forget to file your issue after a task is done. I was hoping the following would work?

```sh
jira add worklog WCMS-2214 -m "Minor JIRA issues + upstream updates" \
                           -T "7h 30m" \
                           -o started="2017-01-29T09:17:00.000-0500" \
                           --noedit
```

**Comment by coryb** [comment]
Added in latest release: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.3

The usage has changed, but this should now work:
```
jira worklog add WCMS-2214 -m "Minor JIRA issues + upstream updates" \
                           -T "7h 30m" \
                           -S "2017-01-29T09:17:00.000-0500" \
                           --noedit
```
