### ISSUE TITLE
Authentication fails (password not stored/used?)

### ISSUE THREAD

**Issue by djui** [Netflix-Skunkworks/go-jira#67]
I'm using version 0.1.9 with a config in `~/.jira.d/config.yml`:

```
endpoint: https://mycompany.atlassian.net
user: myname
password-source: keyring
```

Then I do `jira login` which seems to be fine but I can't see any entry being created in my keychain. Even when creating manually an entry under `go-jira` in the keychain it does not work.

On any request, I need to reenter my password, but the results seem empty:

```
$ jira -v DEV-1234
2017-02-01T00:07:06.720+01:00 INFO  [cli.go:195] GET https://mycompany.atlassian.net/rest/api/2/issue/DEV-1234
Jira Password [myname]: **************************************************
issue: <no value>
summary: <no value>
project: <no value>
reporter:
description: |
```

When typing the wrong password I see:

```
2017-02-01T00:17:00.800+01:00 WARNING [commands.go:68] Login failed
```

I can see that an authentication cookie is written to `~/.jira.d/cookies.js`. It contains a `JSESSIONID` and has an expire of about 1 week.

Also no entry is added to my keychain (macOS) and even when I add the entry `go-jira` there myself, it has no visible effect.

**Comment by djui** [comment]
I think I understand what is the reason for the authentication to fail: You are referring to your own tool packages via `gopkg.in/Netflix-Skunkworks/go-jira.v0`. And this version does not yet have support for  `password-source: keyring`.

After cloning and replacing the package path with the canonical package path and building the `go-jira` binary, it worked.

Please bump the gopkg version to add support for `password-source` and cut a new release.

**Comment by beoran** [comment]
+1 I was also bitten by this issue.

**Comment by coryb** [comment]
Thanks, I have been trying to understand how this is happening.  It looks like an issue with by my build.  In theory jira.v0 and the master branch should be identical, but in this case it looks like I tried to build before the latest tag was pushed.  So the jira.v0 was actually a version behind.  I will fix my build system and cut a new release.  Thanks for finding this!

**Comment by coryb** [comment]
Actually it was easier than I though, I just had some code in the master branch that had not been put in to a release, I guess I forgot at the last work I did on it.  The latest release should work for you:
https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v0.1.10
