### ISSUE TITLE
panic when running commands via ssh

### ISSUE THREAD

**Issue by kfir-drivenets** [Netflix-Skunkworks/go-jira#70]
When I try to run a command I get the following error

```bash
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/guelfey/go%2edbus.sessionBusPlatform(0x80f61e, 0x18, 0x0)
	/home/dn/git/go-jira/src/github.com/guelfey/go.dbus/conn_other.go:26 +0x1fd
github.com/guelfey/go%2edbus.SessionBusPrivate(0x8, 0x820470, 0xc42004be10)
	/home/dn/git/go-jira/src/github.com/guelfey/go.dbus/conn.go:99 +0xc0
github.com/guelfey/go%2edbus.SessionBus(0x0, 0x0, 0x0)
	/home/dn/git/go-jira/src/github.com/guelfey/go.dbus/conn.go:76 +0xc0
github.com/tmc/keyring.init.1()
	/home/dn/git/go-jira/src/github.com/tmc/keyring/keyring_linux.go:144 +0x34
github.com/tmc/keyring.init()
	/home/dn/git/go-jira/src/github.com/tmc/keyring/keyring_linux.go:162 +0xcb
gopkg.in/Netflix-Skunkworks/go-jira%2ev0.init()
	/home/dn/git/go-jira/src/gopkg.in/Netflix-Skunkworks/go-jira.v0/util.go:386 +0xb4
main.init()
	/home/dn/git/go-jira/main/main.go:612 +0x6e
```

Using current master (git commit e80d17d21ee67851ce2dc026f3181637dd7ad196).
When issuing the same command not via ssh it works.

`uname -a` - `Linux dn-VirtualBox 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by coryb** [comment]
What version of `go-jira` are you using?  I looked for`util.go:386` but that file is only 385 lines long now, so looks like some changes were made after your version.  I recommend trying the latest version and see if that fixes your problem:
https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v0.1.11

-Cory

**Comment by coryb** [comment]
Not sure if this is still an issue and have changed how `jira` does authentication and upgraded tmc/keyring to latest.  It looks like dbus related. With the latest auth mechanism perhaps you dont need `password-source` set any more.  If still an issue please reopen.
