### ISSUE TITLE
Stock "edit" template doesn't escape or quote "special" characters

### ISSUE THREAD

**Issue by emarcotte** [Netflix-Skunkworks/go-jira#71]
The stock 'edit' template doesn't do anything about special characters which means that you can't 'round-trip' an issue that has a summary containing something like `Cool:: functions should be cool`

I've not written any go before, if there's a particular escaping function that could be plugged into the template I'd gladly send a pull request, I just need some pointers for where to start!

**Comment by coryb** [comment]
Hey, yeah I need to fix the default templates to make them a bit smarter. There are special characters in yaml that need to be escaped. You can manually add that escaping to work around the issue:
```
summary: "Cool:: functions should be cool"
```

Or this will work:
```
summary: >-
    Cool:: functions should be cool
```
Both will produce the same parsed structure in YAML.

-Cory

**Comment by elsassph** [comment]
Seriously a problem - we can't use any edit commands because we name our issues `[Platform] Description`.

**Comment by coryb** [comment]
@elsassph curious if you were able to use the suggested syntax?
```
summary: >-
    [Platform] Description
```

**Comment by elsassph** [comment]
I added quotes in the template - would you accept a PR changing the default template? To the syntax you seem to prefer.
(thanks for the quick answers BTW)

**Comment by coryb** [comment]
Yeah, I think the `>-` syntax is probably preferable, a PR would be most welcome!

**Comment by coryb** [comment]
Updated all default templates to use the `>-` syntax for summary in latest release.
