### ISSUE TITLE
empty jira response body cause jsonDecode failure when use CmdRequest

### ISSUE THREAD

**Issue by yinchuan** [Netflix-Skunkworks/go-jira#72]
For example, POST to /rest/api/2/issueLink return nothing.
The request actually success, go-jira fail when parse response body which is nothing to json.

output:
> 2017-03-11T10:52:16.335+08:00 ERROR [util.go:247] JSON Parse Error: unexpected end of JSON input from 
> 2017-03-11T10:52:16.336+08:00 ERROR [util.go:219] Failed to execute template: template: template:1:7: executing "template" at <toJson>: wrong number of args for toJson: want 1 got 0
> 2017-03-11T10:52:16.336+08:00 ERROR [main.go:540] template: template:1:7: executing "template" at <toJson>: wrong number of args for toJson: want 1 got 0

use default request template:
```
{{ . | toJson }}
```

**Comment by yinchuan** [comment]
A better way to create `issueLink` is to use `blocks` command, set `issueLinkType` by `-o blockerType=[NAME]`, like below:
```
jira -o blockerType="solve this" ISSUE-01 blocks ISSUE-02
```

**Comment by coryb** [comment]
Thanks for the report yinchuan.  I will try to create better handling for blank responses when using the `req` command.

**Comment by coryb** [comment]
For the latest version `jira req` will now just print `No content in response` when the jira response is empty.
