### ISSUE TITLE
Cannot create issues with required custom fields

### ISSUE THREAD

**Issue by mcallaway** [Netflix-Skunkworks/go-jira#75]
I'm trying to create issues with required custom fields. First I tried this figure out how go-jira sees the field:

    -> ./go-jira create --dryrun -t debug --editor /bin/cat | less
    ... trim the output ...
    "customfield_11348": {
    "allowedValues": [
        {
            "id": "10310",
            "self": "https://jira.gsc.wustl.edu/rest/api/2/customFieldOption/10310",
            "value": "Account Management"
        },
    ... more output trimmed ...
        "hasDefaultValue": false,
        "name": "IT Service",
        "operations": [
            "set"
        ],
        "required": true,
        "schema": {
            "custom": "com.atlassian.jira.plugin.system.customfieldtypes:select",
            "customId": 11348,
            "type": "option"
        }
    },
    ... more output trimmed ...

So now I want to set "customfield_11348" during creation. Each of these three possible attempts fail in the same way:

    -> ./go-jira create -o summary=test -o "IT Service"="Account Management" --noedit
    -> ./go-jira create -o summary=test -o "customfield_11348"="Account Management" --noedit
    -> ./go-jira create -o summary=test -o "cf[11348]"="Account Management" --noedit

The error is:

    {"errorMessages":[],"errors":{"customfield_11348":"IT Service is required."}}

How does one set custom fields?

**Comment by coryb** [comment]
Hmm, not sure you can do it via the `-o` mechanism.  Those will override values that are in the templates.  You might need to create your own template, there are some docs here:
https://github.com/Netflix-Skunkworks/go-jira#templates

I would guess adding something like this would work when put under the `fields:` section of the create template.
```
  # IT Service
  customfield_11348: Account Management
```
Depending on the data type (ie if it is multi-value or not) you might need to pass in an array to the field, that would look something like:
```
  # IT Service
  customfield_11348:
    - name: Account Management
```

If you want to allow command line overrides in the template you should be able to do something like:
```
  # IT Service
  customfield_11348: {{ or .overrides.itservice "" }}
```
Which I think would allow something like: `./jira create -o itservice="Account Management"`

**Comment by mcallaway** [comment]
This works:

    customfield_11348: # Values: {{ range .meta.fields.customfield_11348.allowedValues }}{{.value}}, {{end}} (or .overrides.itservice "")}}
      value: {{ or .overrides.itservice "" }}
