### ISSUE TITLE
Support for OAuth

### ISSUE THREAD

**Issue by rothgar** [Netflix-Skunkworks/go-jira#81]
Is there a way to get the client to work with jira instances that redirect to SSO/OAuth solutions?

My only thought is to grab my cookie from a valid oauth session and maybe use that in config.yml but I'm not sure that would work.

Wanted to ask here in case there's an existing way to make this work or something I'm not thinking of.

**Comment by coryb** [comment]
Currently there is no code to work with SSO/OAuth solutions in `go-jira`.  We have various password management integrations but those are for basic auth.  Unfortunately I don't have any infrastructure where I could even test out SSO since we don't use that at my work, and the Atlassian hosted go-jira.atlassian.net testing site also does not use SSO.  

I would love to take a PR for thisif you are willing to cook up something that will work for you.
-Cory

**Comment by rothgar** [comment]
Thanks for the quick response. Is there a way (config.yml or cli option) to specify the cookie to use? I'm thinking it might be possible to at least send the SSO cookie without any code changes

**Comment by coryb** [comment]
We will send all cookies stored in `$HOME/.jira.d/cookies.js`.  Those cookies are automatically stored when we get a response and are automatically sent back to the service on all subsequent requests.

Perhaps you could submit the sso information via `jira --endpoint https://sso-service.com -M POST req ...` to automatically have cookies cached.

**Comment by rothgar** [comment]
Not sure I'll have time to implement this and don't want to keep a stale issue open for you. Will close and open a PR if I ever get something that works

**Comment by RobHoman** [comment]
For futurecomers, I was able to get this CLI tool to work against JIRA cloud with an OAuth provider as @coryb suggested above by doing the following:
1. Log into JIRA cloud (https://company.atlassian.net)
2. Use my browser dev console to examine the cookies
3. Painstakingly copied the "Name", "Value", "Path", "Domain", "Expires" info (and correspondingly populating the "Raw" field) into the json format expected by the tool in the `~/.jira.d/cookies.js` file. IMPORTANT: you must do this for both `atlassian.xsrf.token` and `cloud.session.token`

Would love to see the tool be able to handle the OAuth dance directly, but stoked to get this workaround up and running.

Hope that helps.

**Comment by dbaumann** [comment]
FWIW @Lupus did some work to add Oauth support to andygrunwald/go-jira, which isn't related, despite the commit referenced above.
https://gist.github.com/Lupus/edafe9a7c5c6b13407293d795442fe67

That implementation provides an http.Client that presumably works with Jira's Oauth 1.0a. It seems like a reasonable investment to incorporate that work into Netflix-Skunkworks/go-jira.

My use case at work is hosted JIRA behind SSO, so I'll get a chance to test this.

**Comment by Lupus** [comment]
I've added CC0 header to the snippet to cover some legal aspects of incorporating code without a defined license, so feel free to do that! :+1:

**Comment by aairey** [comment]
Any example configuration on how to use this?

Ideally I would log in through the browser as I have to through an SSO application.
