### ISSUE TITLE
login doesn't work

### ISSUE THREAD

**Issue by stantonk** [Netflix-Skunkworks/go-jira#82]
I'm sort of at a loss, I've tested my password on the web in a browser and it works, but i can't login from go-jira...any thing I can provide to help debug?

**Comment by stantonk** [comment]
looks like this is the issue?

https://jira.atlassian.com/browse/JRACLOUD-42098

**Comment by coryb** [comment]
Not sure, what authentication scheme does your jira servers use?  If it requires google auth then this is a known issue (#88).

**Comment by coryb** [comment]
I have rewritten go-jira to use the session login api in Jira, not sure if that will work for you or if the G-Suite login is still required for your jira instance. Might want to give the latest version a try:
https://github.com/Netflix-Skunkworks/go-jira#login-process-change

**Comment by coryb** [comment]
closing for now, reopen if still a problem.

**Comment by jottr** [comment]
This is not working for me. I tried with the latest version. 
We have gsuite login enabled with 2FA. 
I tried setting the user to `jira.username` and `jira.username@ourdomain.com`, then tried to provide my gsuite password to `jira login`, which didn't work. 
I'd love to use your plugin though! Can I do anything to help implement G-suite support @coryb?

**Comment by coryb** [comment]
@jottr We have an issue open for gsuite [#88].  I dont have a test environment for that, so cannot implement the functionality.  You can help by providing a PR :)

**Comment by jottr** [comment]
I just found a workaround: One can reset the Atlassian password. This creates a distinct Atlassian password separate from the gsuite login. 
I was able to use said password to login via `jira login`. 

See [here](https://confluence.atlassian.com/cloud/how-g-suite-users-log-in-744721643.html) for further info.
