### ISSUE TITLE
Epic Links

### ISSUE THREAD

**Issue by realmika** [Netflix-Skunkworks/go-jira#87]
Any chance we can set and change Epic Links using GoJira? Might be a GrassHopper thing. Thanks!

**Comment by coryb** [comment]
seems reasonable, but I am not sure what it takes do to this.  It might be as simple as modifying the edit/create templates for your issues in which case you can try to do this yourself.  Here is some documentation on the templates we use and how to modify them:
https://github.com/Netflix-Skunkworks/go-jira#templates

I am unlikely to get this done myself in the near future, but if you or someone else finds a solution I will look into merging any changes into the default templates.

**Comment by gvol** [comment]
For me it was enough to add customfield_11800 to templates.

**Comment by coryb** [comment]
Finally getting some time to look at this, sorry for the delay.  I am not 100% sure what you are talking about, I dont use epics much myself.  I did find some grasshopper apis that might be what you are talking about:

* list issues for epic:
https://docs.atlassian.com/jira-software/REST/latest/#agile/1.0/epic-getIssuesForEpic
* add issues to epic:
https://docs.atlassian.com/jira-software/REST/latest/#agile/1.0/epic-moveIssuesToEpic
* remove issues from epic:
https://docs.atlassian.com/jira-software/REST/latest/#agile/1.0/epic-removeIssuesFromEpic

Do these seem right?  Wondering if an epic specific command would be useful? Something like:
```
jira epic list <EPIC KEY>
jira epic add <EPIC KEY> [ISSUE] [ISSUE]...
jira epic remove <EPIC KEY> [ISSUE] [ISSUE]...
```

**Comment by dhutty** [comment]
Yes, that sounds like just the thing.

**Comment by coryb** [comment]
Cool, thanks for the confirmation @dhutty.  I have started playing around with the code.  I have `jira epic create` coded up to create an issue, I will add the others along with a few tests over the next few days.

**Comment by coryb** [comment]
Okay, I have added various commands for dealing with epics.   Released here:
https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.7

```
$ ./jira epic --help
usage: jira epic <command> [<args> ...]

Flags:
      --help                 Show context-sensitive help (also try --help-long and --help-man).
  -v, --verbose ...          Increase verbosity for debugging
  -e, --endpoint=ENDPOINT    Base URI to use for Jira
  -k, --insecure             Disable TLS certificate verification
  -Q, --quiet                Suppress output to console
      --unixproxy=UNIXPROXY  Path for a unix-socket proxy
  -u, --user=USER            Login name used for authentication with Jira service

Subcommands:
  epic create [<flags>]
    Create Epic

  epic list [<flags>] <EPIC>
    Prints list of issues for an epic with optional search criteria

  epic add <EPIC> <ISSUE>...
    Add issues to Epic

  epic remove <ISSUE>...
    Remove issues from Epic
```

**Comment by realmika** [comment]
Awesome!
