### ISSUE TITLE
Add support for G Suite authentication

### ISSUE THREAD

**Issue by MitchLillie** [Netflix-Skunkworks/go-jira#88]
I'm sure this will go the way of the 2FA issue, but I can't imagine I'm the only one with the G Suite login. Once enabled, no other login methods are possible. See here: https://confluence.atlassian.com/cloud/how-g-suite-users-log-in-744721643.html

**Comment by coryb** [comment]
Yeah, unfortunately, similar to the 2FA issue I can implement something which I cannot test.  I do not have access to a jira backed by the G Suite login.  Would love to take a PR is someone wants to provide the integration work.

**Comment by coryb** [comment]
I have rewritten go-jira to use the `session login` api in Jira, not sure if that will work for you or if the G-Suite login is still required for your jira instance.  Might want to give the latest version a try:
https://github.com/Netflix-Skunkworks/go-jira#login-process-change

**Comment by antonlindstrom** [comment]
I found out that when using the G Suite authentication you can use API Tokens to login. Create an API token here https://id.atlassian.com/manage/api-tokens and use it as a regular Basic Authentication password.

Does this solve the issue for you?

**Comment by MitchLillie** [comment]
@antonlindstrom Actually the API token didn't work for some reason, however I did manage to convince my admin to give me a basic password as well, and I just gave it a shot and it works now. Thanks!

**Comment by rodlogic** [comment]
@antonlindstrom Thanks for this. I was able to successfully use go-jira against a Jira Cloud instance and an API Token:
```
endpoint: https://XXXXXXX.atlassian.net/
login: ME.MEMEME@MEMEMEME.ME
password-source: keyring
```
I then created a new api token using  the https://id.atlassian.com/manage/api-tokens you mentioned above and voila: it worked. You have to enter the token the first time.

**Comment by coryb** [comment]
I have updated the go-jira docs, we now require API Tokens for atlassian.net hosted Jira:
https://github.com/Netflix-Skunkworks/go-jira#authentication

**Comment by coryb** [comment]
@MitchLillie the usual reason the api token does not work is due to the login name missing the domain. 
To support the user vs login dichotomy I had to add an extra `login` config option:
```
user: person
login: person@example.com
```
https://github.com/Netflix-Skunkworks/go-jira#user-vs-login

**Comment by coryb** [comment]
closing, the recommended solution is to use api token.
