### ISSUE TITLE
Transitioning an issue can fail with map fix version value

### ISSUE THREAD

**Issue by bbaugher** [Netflix-Skunkworks/go-jira#89]
Tried to transition an issue with a fix version assigned and it failed with Bad Request,

```
{"errorMessages":[],"errors":{"fixVersions":"Version name 'map[released:false self:https://jira.company.com/rest/api/2/version/25726 id:25726 name:component-0.6.0 archived:false]' is not valid"}}
```

When I choose to edit during the transition I see the fix version value is set to,

```
fields:
  fixVersions: 
    - name: map[self:https://jira.company.com/rest/api/2/version/25726 id:25726 name:component-0.6.0 archived:false released:false]
```

Changing the `name` value to `component-0.6.0` works.

**Comment by coryb** [comment]
Released in 0.1.15
https://github.com/Netflix-Skunkworks/go-jira/releases/latest
