### ISSUE TITLE
"--version" does not print version

### ISSUE THREAD

**Issue by kBite** [Netflix-Skunkworks/go-jira#92]
I'm using Version 0.1.14 of go-jira. I know, because I downloaded it, but `jira` won't tell me it's version:
```
$ sha1sum jira
46cd0dcb8b7ffd074191e3e6fc0e6bfc347ee4d5  jira
$ jira --version
version:
```

**Comment by coryb** [comment]
Thanks, it is a dumb issue with the build that I need to fix.

**Comment by coryb** [comment]
Works now, although I changed the --version to a `version` command:
```
$ jira version
1.0.1
```
