### ISSUE TITLE
Additional documentation on how "--queryfields" works

### ISSUE THREAD

**Issue by dotwaffle** [Netflix-Skunkworks/go-jira#95]
I'm currently doing a query which outputs:

```
PROJECT-1234:   Summary of 1234
PROJECT-2345:   Summary of 2345
```

As I'm using the output as a sort of "see what to do next" thing, it'd be excellent if I could output the date of last update (either in ISO8601, or maybe fancy "3 hours ago" format) which I assumed was doable with `--queryfields=created,updated,summary` but that outputs exactly the same data.

The command I'm using at the moment is (obfuscated):

`jira list -q 'project = PROJECT AND status = "Pending" AND assignee in (currentUser()) AND updatedDate < startOfDay(-1) ORDER BY updatedDate ASC' -f updated,summary`

Is it possible to get a little documentation on that option, or a pointer as to how I can format the output myself?

**Comment by mickgardner** [comment]
+1

**Comment by coryb** [comment]
Sorry for the laggy response.  The queryfields are basically just the default list of fields to fetch from jira for the search api.  To make the search api fast jira does not return most of the issue fields, so if you want special fields for displaying then you have to ask for those explicitly.  The default fields in `go-jira` are just the fields we use in the default templates.  So overriding `queryfields` will allow you to make additional fields made available to the view template.  To see the raw data that jira sends back you can use the `debug` template (with `-t debug`), which will just dump the raw JSON.

The template that is used by default for the `list` command is:
```
{{ range .issues }}{{ .key | append \":\" | printf \"%-12s\"}} {{ .fields.summary }}\n{{ end }}
```
This basically  loops over all issues, prints out the `key` with some formatting, then prints out the summary field.  If you want to also print out the updated field it would be something like:
```
{{ range .issues }}{{ .key | append \":\" | printf \"%-12s\"}} {{ .fields.summary }} - {{ .fields.updated}}\n{{ end }}
```
That will be the raw `updated` field (ie whatever time format jira returns), if you want it to print something like `3 hours ago` you can use the `age` template filter like:
```
{{ .fields.updated | age}} ago
```

To use a custom template you can just write it to a file and use it directly so you can create `myview.tmpl` and use it with `jira list -t ./myview.tmpl`.  If you want your customized template to be used by default for the `list` view then you can just save your template as `~/.jira.d/templates/list`

**Comment by dotwaffle** [comment]
I think that solves my use case... Just wondered if there was an easier way of showing fields when specified, but I guess the flexibility of the template system makes more sense.

Thank you for the response!

**Comment by AndresPineros** [comment]
Although it would be nice to specify the template in the command. Having to create a template file for simple patterns is annoying.

Something like:
`jira list --script-template="{{ range .issues }}{{.key}}{{end}}"`
