### ISSUE TITLE
Would you consider vendoring your dependencies?

### ISSUE THREAD

**Issue by williamh** [Netflix-Skunkworks/go-jira#96]
Hello,

current versions of Go support a vendor folder where you can place all of your external dependencies.  The advantage of this is that it allows you to lock down your dependencies so that go build doesn't go out and pull down newer versions of them that could break the build.

Are you willing to consider using this feature with go-jira?
It would make things easier for distro packagers.

Thanks for your time. :-)

William

**Comment by coryb** [comment]
Yup, know all about vendoring and use it on most of my projects.  `go-jira` is old code and *very* 
ugly.  I need to spend a lot of time cleaning it up, including vendoring and purging all the `interface{}` nonsense.   Hopefully I can get some time for it this weekend.

**Comment by williamh** [comment]
Let me know if I can help some how. I'm not yet an expert in Go, but I am interested in this project because I want to use it to access my company's Jira.

**Comment by coryb** [comment]
I have rewritten go-jira and as part of that I now vendor all the deps.
