### ISSUE TITLE
jira ls enhancements

### ISSUE THREAD

**Issue by williamh** [Netflix-Skunkworks/go-jira#98]
Hello again,

I noticed that "jira ls" doesn't have options for status.

It would be very helpful if "jira ls" had options that would allow me to list statuses of issues that I either want to see or do not want to see in the output.

Is this something you would consider adding?

Thanks for your time. :-)

**Comment by coryb** [comment]
So you are looking for something like `jira ls --status done`?  Or are you asking to see a `Status` column in the output?   You can probably also implement this on your own via a custom template which you can read more about here: https://github.com/Netflix-Skunkworks/go-jira#templates

**Comment by williamh** [comment]
I figured out how to control the output; I am looking to query issues based on status, so a couple of options possibly:

```
jira ls --status 'to do' --status 'in progress ...
```

to list issues that have those statuses, or

```
jira ls --exclude-status 'to do' --exclude-status 'in progress ...
```

to list issues that do _not_ have those statuses.

**Comment by coryb** [comment]
Fwiw, you can also modify the jql directly via the `--query` option. This will include status:
```
jira ls --query "resolution = unresolved AND project = '<project>' AND status = 'To Do'" 
```
This will exclude status:
```
jira ls --query "resolution = unresolved AND project = '<project>' AND status not in ('To Do', 'In Progress')"
```

**Comment by coryb** [comment]
I have added the `--status` option, for more complex cases like the `AND status != "To Do"` and for querying on multiple statuses, I think it is probably more appropriate to just have a stored query for this, so for more complicated stuff I am planning on adding something like #99.

**Comment by coryb** [comment]
Changed released: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.6
