### ISSUE TITLE
save queries in configuration file

### ISSUE THREAD

**Issue by williamh** [Netflix-Skunkworks/go-jira#99]
My co-worker and I cane up with another possible enhancement to this tool.

The -q option allows jql on the command line. It would be cool if there were a way to save jql queries in .jira.d and refer to them by name on the command line.

We could use a command line option, for example -Q (note upper case) to refer to a query like this:

```
jira ls -Q myquery
```

I thought about saving the queries themselves in config.yml, but I'm not sure if that would work or what the syntax would be. My thought is a "queries" dictionary in which the key is the name and the value is the jql query itself, but I'm not quite sure what that would look like.

What are your thoughts about something like this? If you give me the information, I may look into submitting a pull request for this.

Thanks,

William

**Comment by williamh** [comment]
Ok, it looks like we couldn't use -Q for this, because it is already used for --quiet.

**Comment by gvol** [comment]
Something like the following works for me to allow usage like `jira foo` and `jira bar`:

    # Default configuration here...


    # Only for certain types
    case $JIRA_OPERATION in

        foo)
            cat <<EOF
    command: list
    query: filter = 12345
    EOF
            ;;

        bar)
            cat <<EOF
    command: list
    query: user = currentUser() and Sprint in openSprints()
    EOF
            ;;
    esac

**Comment by williamh** [comment]
I am looking for a convenient way to list all tickets assigned to me that are not resolved. How do you suggest doing this?

Thanks much,

William

**Comment by gvol** [comment]
Here's an abbreviated and redacted version of what I have, which allows me to run `jira mine` and see what's assigned to me.  I save a filter in Jira that links to my issues (numbered 12345 in this example).

```
#!/usr/local/bin/bash

cat <<EOF
endpoint: https://jira.xxxx.xxxx/
project: XXX
components: XXXX
priority: Normal
EOF

case $JIRA_OPERATION in
    mine)
        cat <<EOF
command: list
query: filter = 12345
EOF
        ;;
esac
```

I find it works quite well.

**Comment by coryb** [comment]
I have created an example for how to create `jira mine` command to list issues assigned to you:
https://github.com/Netflix-Skunkworks/go-jira#examples

It no longer uses the executable config file, but that mechanism should still work.

Still thinking named queries might be useful also, perhaps something like:
```
named-queries:
  foo: filter = 12345
  bar: user = currentUser() and Sprint in openSprints()
```
Then modify the list/edit usage to access the via:
```
jira ls -N foo
jira ls --named foo
```

**Comment by coryb** [comment]
Added named queries into `.jira.d/configs.yml`:
```
queries:
  todo: |
    resolution = unresolved {{if .project}}AND project = '{{.project}}'{{end}} AND status = 'To Do'
  open: |
    resolution = unresolved {{if .project}}AND project = '{{.project}}'{{end}} AND status = 'Open'
```
They can be templates and can use command line options and configs to populate:
```
$ jira ls --named-query todo
+----------------+---------------+--------------+--------------+------------+--------------+--------------+
| Issue          | Summary       | Priority     | Status       | Age        | Reporter     | Assignee     |
+----------------+---------------+--------------+--------------+------------+--------------+--------------+
| TASK-258       | summary       | Medium       | To Do        | an hour    | gojira       | gojira       |
| SCRUM-267      | summary       | Medium       | To Do        | an hour    | gojira       | gojira       |
| PROJECT-252    | summary       | Medium       | To Do        | an hour    | gojira       | gojira       |
| BASIC-450      | summary       | Medium       | To Do        | an hour    | gojira       | gojira       |
+----------------+---------------+--------------+--------------+------------+--------------+--------------+
```

```
$ jira ls -n todo -p BASIC
+----------------+---------------+--------------+--------------+------------+--------------+--------------+
| Issue          | Summary       | Priority     | Status       | Age        | Reporter     | Assignee     |
+----------------+---------------+--------------+--------------+------------+--------------+--------------+
| BASIC-450      | summary       | Medium       | To Do        | an hour    | gojira       | gojira       |
+----------------+---------------+--------------+--------------+------------+--------------+--------------+
```

**Comment by coryb** [comment]
Changed released here: https://github.com/Netflix-Skunkworks/go-jira/releases/tag/v1.0.6
